// Auto-generated Unicode confusables map (1573 entries)
// Source: Python unicodedata NFKC/NFKD decompositions
// Covers: accented letters, mathematical symbols, enclosed alphanumerics,
//         fullwidth forms, script variants, and other visual confusables.
//
// This replaces the hand-curated HOMOGLYPH_MAP with comprehensive coverage.

pub static CONFUSABLES: &[(char, char)] = &[
    // ---- Latin Extended / Diacritics ----
    ('\u{00AA}', 'a'), // FEMININE ORDINAL INDICATOR
    ('\u{00B2}', '2'), // SUPERSCRIPT TWO
    ('\u{00B3}', '3'), // SUPERSCRIPT THREE
    ('\u{00B9}', '1'), // SUPERSCRIPT ONE
    ('\u{00BA}', 'o'), // MASCULINE ORDINAL INDICATOR
    ('\u{00C0}', 'A'), // LATIN CAPITAL LETTER A WITH GRAVE
    ('\u{00C1}', 'A'), // LATIN CAPITAL LETTER A WITH ACUTE
    ('\u{00C2}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    ('\u{00C3}', 'A'), // LATIN CAPITAL LETTER A WITH TILDE
    ('\u{00C4}', 'A'), // LATIN CAPITAL LETTER A WITH DIAERESIS
    ('\u{00C5}', 'A'), // LATIN CAPITAL LETTER A WITH RING ABOVE
    ('\u{00C7}', 'C'), // LATIN CAPITAL LETTER C WITH CEDILLA
    ('\u{00C8}', 'E'), // LATIN CAPITAL LETTER E WITH GRAVE
    ('\u{00C9}', 'E'), // LATIN CAPITAL LETTER E WITH ACUTE
    ('\u{00CA}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    ('\u{00CB}', 'E'), // LATIN CAPITAL LETTER E WITH DIAERESIS
    ('\u{00CC}', 'I'), // LATIN CAPITAL LETTER I WITH GRAVE
    ('\u{00CD}', 'I'), // LATIN CAPITAL LETTER I WITH ACUTE
    ('\u{00CE}', 'I'), // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    ('\u{00CF}', 'I'), // LATIN CAPITAL LETTER I WITH DIAERESIS
    ('\u{00D1}', 'N'), // LATIN CAPITAL LETTER N WITH TILDE
    ('\u{00D2}', 'O'), // LATIN CAPITAL LETTER O WITH GRAVE
    ('\u{00D3}', 'O'), // LATIN CAPITAL LETTER O WITH ACUTE
    ('\u{00D4}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    ('\u{00D5}', 'O'), // LATIN CAPITAL LETTER O WITH TILDE
    ('\u{00D6}', 'O'), // LATIN CAPITAL LETTER O WITH DIAERESIS
    ('\u{00D9}', 'U'), // LATIN CAPITAL LETTER U WITH GRAVE
    ('\u{00DA}', 'U'), // LATIN CAPITAL LETTER U WITH ACUTE
    ('\u{00DB}', 'U'), // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    ('\u{00DC}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS
    ('\u{00DD}', 'Y'), // LATIN CAPITAL LETTER Y WITH ACUTE
    ('\u{00E0}', 'a'), // LATIN SMALL LETTER A WITH GRAVE
    ('\u{00E1}', 'a'), // LATIN SMALL LETTER A WITH ACUTE
    ('\u{00E2}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX
    ('\u{00E3}', 'a'), // LATIN SMALL LETTER A WITH TILDE
    ('\u{00E4}', 'a'), // LATIN SMALL LETTER A WITH DIAERESIS
    ('\u{00E5}', 'a'), // LATIN SMALL LETTER A WITH RING ABOVE
    ('\u{00E7}', 'c'), // LATIN SMALL LETTER C WITH CEDILLA
    ('\u{00E8}', 'e'), // LATIN SMALL LETTER E WITH GRAVE
    ('\u{00E9}', 'e'), // LATIN SMALL LETTER E WITH ACUTE
    ('\u{00EA}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX
    ('\u{00EB}', 'e'), // LATIN SMALL LETTER E WITH DIAERESIS
    ('\u{00EC}', 'i'), // LATIN SMALL LETTER I WITH GRAVE
    ('\u{00ED}', 'i'), // LATIN SMALL LETTER I WITH ACUTE
    ('\u{00EE}', 'i'), // LATIN SMALL LETTER I WITH CIRCUMFLEX
    ('\u{00EF}', 'i'), // LATIN SMALL LETTER I WITH DIAERESIS
    ('\u{00F1}', 'n'), // LATIN SMALL LETTER N WITH TILDE
    ('\u{00F2}', 'o'), // LATIN SMALL LETTER O WITH GRAVE
    ('\u{00F3}', 'o'), // LATIN SMALL LETTER O WITH ACUTE
    ('\u{00F4}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX
    ('\u{00F5}', 'o'), // LATIN SMALL LETTER O WITH TILDE
    ('\u{00F6}', 'o'), // LATIN SMALL LETTER O WITH DIAERESIS
    ('\u{00F9}', 'u'), // LATIN SMALL LETTER U WITH GRAVE
    ('\u{00FA}', 'u'), // LATIN SMALL LETTER U WITH ACUTE
    ('\u{00FB}', 'u'), // LATIN SMALL LETTER U WITH CIRCUMFLEX
    ('\u{00FC}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS
    ('\u{00FD}', 'y'), // LATIN SMALL LETTER Y WITH ACUTE
    ('\u{00FF}', 'y'), // LATIN SMALL LETTER Y WITH DIAERESIS
    ('\u{0100}', 'A'), // LATIN CAPITAL LETTER A WITH MACRON
    ('\u{0101}', 'a'), // LATIN SMALL LETTER A WITH MACRON
    ('\u{0102}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE
    ('\u{0103}', 'a'), // LATIN SMALL LETTER A WITH BREVE
    ('\u{0104}', 'A'), // LATIN CAPITAL LETTER A WITH OGONEK
    ('\u{0105}', 'a'), // LATIN SMALL LETTER A WITH OGONEK
    ('\u{0106}', 'C'), // LATIN CAPITAL LETTER C WITH ACUTE
    ('\u{0107}', 'c'), // LATIN SMALL LETTER C WITH ACUTE
    ('\u{0108}', 'C'), // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    ('\u{0109}', 'c'), // LATIN SMALL LETTER C WITH CIRCUMFLEX
    ('\u{010A}', 'C'), // LATIN CAPITAL LETTER C WITH DOT ABOVE
    ('\u{010B}', 'c'), // LATIN SMALL LETTER C WITH DOT ABOVE
    ('\u{010C}', 'C'), // LATIN CAPITAL LETTER C WITH CARON
    ('\u{010D}', 'c'), // LATIN SMALL LETTER C WITH CARON
    ('\u{010E}', 'D'), // LATIN CAPITAL LETTER D WITH CARON
    ('\u{010F}', 'd'), // LATIN SMALL LETTER D WITH CARON
    ('\u{0112}', 'E'), // LATIN CAPITAL LETTER E WITH MACRON
    ('\u{0113}', 'e'), // LATIN SMALL LETTER E WITH MACRON
    ('\u{0114}', 'E'), // LATIN CAPITAL LETTER E WITH BREVE
    ('\u{0115}', 'e'), // LATIN SMALL LETTER E WITH BREVE
    ('\u{0116}', 'E'), // LATIN CAPITAL LETTER E WITH DOT ABOVE
    ('\u{0117}', 'e'), // LATIN SMALL LETTER E WITH DOT ABOVE
    ('\u{0118}', 'E'), // LATIN CAPITAL LETTER E WITH OGONEK
    ('\u{0119}', 'e'), // LATIN SMALL LETTER E WITH OGONEK
    ('\u{011A}', 'E'), // LATIN CAPITAL LETTER E WITH CARON
    ('\u{011B}', 'e'), // LATIN SMALL LETTER E WITH CARON
    ('\u{011C}', 'G'), // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    ('\u{011D}', 'g'), // LATIN SMALL LETTER G WITH CIRCUMFLEX
    ('\u{011E}', 'G'), // LATIN CAPITAL LETTER G WITH BREVE
    ('\u{011F}', 'g'), // LATIN SMALL LETTER G WITH BREVE
    ('\u{0120}', 'G'), // LATIN CAPITAL LETTER G WITH DOT ABOVE
    ('\u{0121}', 'g'), // LATIN SMALL LETTER G WITH DOT ABOVE
    ('\u{0122}', 'G'), // LATIN CAPITAL LETTER G WITH CEDILLA
    ('\u{0123}', 'g'), // LATIN SMALL LETTER G WITH CEDILLA
    ('\u{0124}', 'H'), // LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    ('\u{0125}', 'h'), // LATIN SMALL LETTER H WITH CIRCUMFLEX
    ('\u{0128}', 'I'), // LATIN CAPITAL LETTER I WITH TILDE
    ('\u{0129}', 'i'), // LATIN SMALL LETTER I WITH TILDE
    ('\u{012A}', 'I'), // LATIN CAPITAL LETTER I WITH MACRON
    ('\u{012B}', 'i'), // LATIN SMALL LETTER I WITH MACRON
    ('\u{012C}', 'I'), // LATIN CAPITAL LETTER I WITH BREVE
    ('\u{012D}', 'i'), // LATIN SMALL LETTER I WITH BREVE
    ('\u{012E}', 'I'), // LATIN CAPITAL LETTER I WITH OGONEK
    ('\u{012F}', 'i'), // LATIN SMALL LETTER I WITH OGONEK
    ('\u{0130}', 'I'), // LATIN CAPITAL LETTER I WITH DOT ABOVE
    ('\u{0134}', 'J'), // LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    ('\u{0135}', 'j'), // LATIN SMALL LETTER J WITH CIRCUMFLEX
    ('\u{0136}', 'K'), // LATIN CAPITAL LETTER K WITH CEDILLA
    ('\u{0137}', 'k'), // LATIN SMALL LETTER K WITH CEDILLA
    ('\u{0139}', 'L'), // LATIN CAPITAL LETTER L WITH ACUTE
    ('\u{013A}', 'l'), // LATIN SMALL LETTER L WITH ACUTE
    ('\u{013B}', 'L'), // LATIN CAPITAL LETTER L WITH CEDILLA
    ('\u{013C}', 'l'), // LATIN SMALL LETTER L WITH CEDILLA
    ('\u{013D}', 'L'), // LATIN CAPITAL LETTER L WITH CARON
    ('\u{013E}', 'l'), // LATIN SMALL LETTER L WITH CARON
    ('\u{0143}', 'N'), // LATIN CAPITAL LETTER N WITH ACUTE
    ('\u{0144}', 'n'), // LATIN SMALL LETTER N WITH ACUTE
    ('\u{0145}', 'N'), // LATIN CAPITAL LETTER N WITH CEDILLA
    ('\u{0146}', 'n'), // LATIN SMALL LETTER N WITH CEDILLA
    ('\u{0147}', 'N'), // LATIN CAPITAL LETTER N WITH CARON
    ('\u{0148}', 'n'), // LATIN SMALL LETTER N WITH CARON
    ('\u{014C}', 'O'), // LATIN CAPITAL LETTER O WITH MACRON
    ('\u{014D}', 'o'), // LATIN SMALL LETTER O WITH MACRON
    ('\u{014E}', 'O'), // LATIN CAPITAL LETTER O WITH BREVE
    ('\u{014F}', 'o'), // LATIN SMALL LETTER O WITH BREVE
    ('\u{0150}', 'O'), // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    ('\u{0151}', 'o'), // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    ('\u{0154}', 'R'), // LATIN CAPITAL LETTER R WITH ACUTE
    ('\u{0155}', 'r'), // LATIN SMALL LETTER R WITH ACUTE
    ('\u{0156}', 'R'), // LATIN CAPITAL LETTER R WITH CEDILLA
    ('\u{0157}', 'r'), // LATIN SMALL LETTER R WITH CEDILLA
    ('\u{0158}', 'R'), // LATIN CAPITAL LETTER R WITH CARON
    ('\u{0159}', 'r'), // LATIN SMALL LETTER R WITH CARON
    ('\u{015A}', 'S'), // LATIN CAPITAL LETTER S WITH ACUTE
    ('\u{015B}', 's'), // LATIN SMALL LETTER S WITH ACUTE
    ('\u{015C}', 'S'), // LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    ('\u{015D}', 's'), // LATIN SMALL LETTER S WITH CIRCUMFLEX
    ('\u{015E}', 'S'), // LATIN CAPITAL LETTER S WITH CEDILLA
    ('\u{015F}', 's'), // LATIN SMALL LETTER S WITH CEDILLA
    ('\u{0160}', 'S'), // LATIN CAPITAL LETTER S WITH CARON
    ('\u{0161}', 's'), // LATIN SMALL LETTER S WITH CARON
    ('\u{0162}', 'T'), // LATIN CAPITAL LETTER T WITH CEDILLA
    ('\u{0163}', 't'), // LATIN SMALL LETTER T WITH CEDILLA
    ('\u{0164}', 'T'), // LATIN CAPITAL LETTER T WITH CARON
    ('\u{0165}', 't'), // LATIN SMALL LETTER T WITH CARON
    ('\u{0168}', 'U'), // LATIN CAPITAL LETTER U WITH TILDE
    ('\u{0169}', 'u'), // LATIN SMALL LETTER U WITH TILDE
    ('\u{016A}', 'U'), // LATIN CAPITAL LETTER U WITH MACRON
    ('\u{016B}', 'u'), // LATIN SMALL LETTER U WITH MACRON
    ('\u{016C}', 'U'), // LATIN CAPITAL LETTER U WITH BREVE
    ('\u{016D}', 'u'), // LATIN SMALL LETTER U WITH BREVE
    ('\u{016E}', 'U'), // LATIN CAPITAL LETTER U WITH RING ABOVE
    ('\u{016F}', 'u'), // LATIN SMALL LETTER U WITH RING ABOVE
    ('\u{0170}', 'U'), // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    ('\u{0171}', 'u'), // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    ('\u{0172}', 'U'), // LATIN CAPITAL LETTER U WITH OGONEK
    ('\u{0173}', 'u'), // LATIN SMALL LETTER U WITH OGONEK
    ('\u{0174}', 'W'), // LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    ('\u{0175}', 'w'), // LATIN SMALL LETTER W WITH CIRCUMFLEX
    ('\u{0176}', 'Y'), // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    ('\u{0177}', 'y'), // LATIN SMALL LETTER Y WITH CIRCUMFLEX
    ('\u{0178}', 'Y'), // LATIN CAPITAL LETTER Y WITH DIAERESIS
    ('\u{0179}', 'Z'), // LATIN CAPITAL LETTER Z WITH ACUTE
    ('\u{017A}', 'z'), // LATIN SMALL LETTER Z WITH ACUTE
    ('\u{017B}', 'Z'), // LATIN CAPITAL LETTER Z WITH DOT ABOVE
    ('\u{017C}', 'z'), // LATIN SMALL LETTER Z WITH DOT ABOVE
    ('\u{017D}', 'Z'), // LATIN CAPITAL LETTER Z WITH CARON
    ('\u{017E}', 'z'), // LATIN SMALL LETTER Z WITH CARON
    ('\u{017F}', 's'), // LATIN SMALL LETTER LONG S
    ('\u{01A0}', 'O'), // LATIN CAPITAL LETTER O WITH HORN
    ('\u{01A1}', 'o'), // LATIN SMALL LETTER O WITH HORN
    ('\u{01AF}', 'U'), // LATIN CAPITAL LETTER U WITH HORN
    ('\u{01B0}', 'u'), // LATIN SMALL LETTER U WITH HORN
    ('\u{01CD}', 'A'), // LATIN CAPITAL LETTER A WITH CARON
    ('\u{01CE}', 'a'), // LATIN SMALL LETTER A WITH CARON
    ('\u{01CF}', 'I'), // LATIN CAPITAL LETTER I WITH CARON
    ('\u{01D0}', 'i'), // LATIN SMALL LETTER I WITH CARON
    ('\u{01D1}', 'O'), // LATIN CAPITAL LETTER O WITH CARON
    ('\u{01D2}', 'o'), // LATIN SMALL LETTER O WITH CARON
    ('\u{01D3}', 'U'), // LATIN CAPITAL LETTER U WITH CARON
    ('\u{01D4}', 'u'), // LATIN SMALL LETTER U WITH CARON
    ('\u{01D5}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
    ('\u{01D6}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
    ('\u{01D7}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
    ('\u{01D8}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
    ('\u{01D9}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
    ('\u{01DA}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS AND CARON
    ('\u{01DB}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
    ('\u{01DC}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
    ('\u{01DE}', 'A'), // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
    ('\u{01DF}', 'a'), // LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
    ('\u{01E0}', 'A'), // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
    ('\u{01E1}', 'a'), // LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
    ('\u{01E6}', 'G'), // LATIN CAPITAL LETTER G WITH CARON
    ('\u{01E7}', 'g'), // LATIN SMALL LETTER G WITH CARON
    ('\u{01E8}', 'K'), // LATIN CAPITAL LETTER K WITH CARON
    ('\u{01E9}', 'k'), // LATIN SMALL LETTER K WITH CARON
    ('\u{01EA}', 'O'), // LATIN CAPITAL LETTER O WITH OGONEK
    ('\u{01EB}', 'o'), // LATIN SMALL LETTER O WITH OGONEK
    ('\u{01EC}', 'O'), // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
    ('\u{01ED}', 'o'), // LATIN SMALL LETTER O WITH OGONEK AND MACRON
    ('\u{01F0}', 'j'), // LATIN SMALL LETTER J WITH CARON
    ('\u{01F4}', 'G'), // LATIN CAPITAL LETTER G WITH ACUTE
    ('\u{01F5}', 'g'), // LATIN SMALL LETTER G WITH ACUTE
    ('\u{01F8}', 'N'), // LATIN CAPITAL LETTER N WITH GRAVE
    ('\u{01F9}', 'n'), // LATIN SMALL LETTER N WITH GRAVE
    ('\u{01FA}', 'A'), // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
    ('\u{01FB}', 'a'), // LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    ('\u{0200}', 'A'), // LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
    ('\u{0201}', 'a'), // LATIN SMALL LETTER A WITH DOUBLE GRAVE
    ('\u{0202}', 'A'), // LATIN CAPITAL LETTER A WITH INVERTED BREVE
    ('\u{0203}', 'a'), // LATIN SMALL LETTER A WITH INVERTED BREVE
    ('\u{0204}', 'E'), // LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
    ('\u{0205}', 'e'), // LATIN SMALL LETTER E WITH DOUBLE GRAVE
    ('\u{0206}', 'E'), // LATIN CAPITAL LETTER E WITH INVERTED BREVE
    ('\u{0207}', 'e'), // LATIN SMALL LETTER E WITH INVERTED BREVE
    ('\u{0208}', 'I'), // LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
    ('\u{0209}', 'i'), // LATIN SMALL LETTER I WITH DOUBLE GRAVE
    ('\u{020A}', 'I'), // LATIN CAPITAL LETTER I WITH INVERTED BREVE
    ('\u{020B}', 'i'), // LATIN SMALL LETTER I WITH INVERTED BREVE
    ('\u{020C}', 'O'), // LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
    ('\u{020D}', 'o'), // LATIN SMALL LETTER O WITH DOUBLE GRAVE
    ('\u{020E}', 'O'), // LATIN CAPITAL LETTER O WITH INVERTED BREVE
    ('\u{020F}', 'o'), // LATIN SMALL LETTER O WITH INVERTED BREVE
    ('\u{0210}', 'R'), // LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
    ('\u{0211}', 'r'), // LATIN SMALL LETTER R WITH DOUBLE GRAVE
    ('\u{0212}', 'R'), // LATIN CAPITAL LETTER R WITH INVERTED BREVE
    ('\u{0213}', 'r'), // LATIN SMALL LETTER R WITH INVERTED BREVE
    ('\u{0214}', 'U'), // LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
    ('\u{0215}', 'u'), // LATIN SMALL LETTER U WITH DOUBLE GRAVE
    ('\u{0216}', 'U'), // LATIN CAPITAL LETTER U WITH INVERTED BREVE
    ('\u{0217}', 'u'), // LATIN SMALL LETTER U WITH INVERTED BREVE
    ('\u{0218}', 'S'), // LATIN CAPITAL LETTER S WITH COMMA BELOW
    ('\u{0219}', 's'), // LATIN SMALL LETTER S WITH COMMA BELOW
    ('\u{021A}', 'T'), // LATIN CAPITAL LETTER T WITH COMMA BELOW
    ('\u{021B}', 't'), // LATIN SMALL LETTER T WITH COMMA BELOW
    ('\u{021E}', 'H'), // LATIN CAPITAL LETTER H WITH CARON
    ('\u{021F}', 'h'), // LATIN SMALL LETTER H WITH CARON
    ('\u{0226}', 'A'), // LATIN CAPITAL LETTER A WITH DOT ABOVE
    ('\u{0227}', 'a'), // LATIN SMALL LETTER A WITH DOT ABOVE
    ('\u{0228}', 'E'), // LATIN CAPITAL LETTER E WITH CEDILLA
    ('\u{0229}', 'e'), // LATIN SMALL LETTER E WITH CEDILLA
    ('\u{022A}', 'O'), // LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
    ('\u{022B}', 'o'), // LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
    ('\u{022C}', 'O'), // LATIN CAPITAL LETTER O WITH TILDE AND MACRON
    ('\u{022D}', 'o'), // LATIN SMALL LETTER O WITH TILDE AND MACRON
    ('\u{022E}', 'O'), // LATIN CAPITAL LETTER O WITH DOT ABOVE
    ('\u{022F}', 'o'), // LATIN SMALL LETTER O WITH DOT ABOVE
    ('\u{0230}', 'O'), // LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
    ('\u{0231}', 'o'), // LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
    ('\u{0232}', 'Y'), // LATIN CAPITAL LETTER Y WITH MACRON
    ('\u{0233}', 'y'), // LATIN SMALL LETTER Y WITH MACRON
    ('\u{02B0}', 'h'), // MODIFIER LETTER SMALL H
    ('\u{02B2}', 'j'), // MODIFIER LETTER SMALL J
    ('\u{02B3}', 'r'), // MODIFIER LETTER SMALL R
    ('\u{02B7}', 'w'), // MODIFIER LETTER SMALL W
    ('\u{02B8}', 'y'), // MODIFIER LETTER SMALL Y
    ('\u{02E1}', 'l'), // MODIFIER LETTER SMALL L
    ('\u{02E2}', 's'), // MODIFIER LETTER SMALL S
    ('\u{02E3}', 'x'), // MODIFIER LETTER SMALL X
    // ---- Cyrillic / Greek ----
    ('\u{037E}', ';'), // GREEK QUESTION MARK
    // ---- Various scripts ----
    ('\u{1D2C}', 'A'), // MODIFIER LETTER CAPITAL A
    ('\u{1D2E}', 'B'), // MODIFIER LETTER CAPITAL B
    ('\u{1D30}', 'D'), // MODIFIER LETTER CAPITAL D
    ('\u{1D31}', 'E'), // MODIFIER LETTER CAPITAL E
    ('\u{1D33}', 'G'), // MODIFIER LETTER CAPITAL G
    ('\u{1D34}', 'H'), // MODIFIER LETTER CAPITAL H
    ('\u{1D35}', 'I'), // MODIFIER LETTER CAPITAL I
    ('\u{1D36}', 'J'), // MODIFIER LETTER CAPITAL J
    ('\u{1D37}', 'K'), // MODIFIER LETTER CAPITAL K
    ('\u{1D38}', 'L'), // MODIFIER LETTER CAPITAL L
    ('\u{1D39}', 'M'), // MODIFIER LETTER CAPITAL M
    ('\u{1D3A}', 'N'), // MODIFIER LETTER CAPITAL N
    ('\u{1D3C}', 'O'), // MODIFIER LETTER CAPITAL O
    ('\u{1D3E}', 'P'), // MODIFIER LETTER CAPITAL P
    ('\u{1D3F}', 'R'), // MODIFIER LETTER CAPITAL R
    ('\u{1D40}', 'T'), // MODIFIER LETTER CAPITAL T
    ('\u{1D41}', 'U'), // MODIFIER LETTER CAPITAL U
    ('\u{1D42}', 'W'), // MODIFIER LETTER CAPITAL W
    ('\u{1D43}', 'a'), // MODIFIER LETTER SMALL A
    ('\u{1D47}', 'b'), // MODIFIER LETTER SMALL B
    ('\u{1D48}', 'd'), // MODIFIER LETTER SMALL D
    ('\u{1D49}', 'e'), // MODIFIER LETTER SMALL E
    ('\u{1D4D}', 'g'), // MODIFIER LETTER SMALL G
    ('\u{1D4F}', 'k'), // MODIFIER LETTER SMALL K
    ('\u{1D50}', 'm'), // MODIFIER LETTER SMALL M
    ('\u{1D52}', 'o'), // MODIFIER LETTER SMALL O
    ('\u{1D56}', 'p'), // MODIFIER LETTER SMALL P
    ('\u{1D57}', 't'), // MODIFIER LETTER SMALL T
    ('\u{1D58}', 'u'), // MODIFIER LETTER SMALL U
    ('\u{1D5B}', 'v'), // MODIFIER LETTER SMALL V
    ('\u{1D62}', 'i'), // LATIN SUBSCRIPT SMALL LETTER I
    ('\u{1D63}', 'r'), // LATIN SUBSCRIPT SMALL LETTER R
    ('\u{1D64}', 'u'), // LATIN SUBSCRIPT SMALL LETTER U
    ('\u{1D65}', 'v'), // LATIN SUBSCRIPT SMALL LETTER V
    ('\u{1D9C}', 'c'), // MODIFIER LETTER SMALL C
    ('\u{1DA0}', 'f'), // MODIFIER LETTER SMALL F
    ('\u{1DBB}', 'z'), // MODIFIER LETTER SMALL Z
    ('\u{1E00}', 'A'), // LATIN CAPITAL LETTER A WITH RING BELOW
    ('\u{1E01}', 'a'), // LATIN SMALL LETTER A WITH RING BELOW
    ('\u{1E02}', 'B'), // LATIN CAPITAL LETTER B WITH DOT ABOVE
    ('\u{1E03}', 'b'), // LATIN SMALL LETTER B WITH DOT ABOVE
    ('\u{1E04}', 'B'), // LATIN CAPITAL LETTER B WITH DOT BELOW
    ('\u{1E05}', 'b'), // LATIN SMALL LETTER B WITH DOT BELOW
    ('\u{1E06}', 'B'), // LATIN CAPITAL LETTER B WITH LINE BELOW
    ('\u{1E07}', 'b'), // LATIN SMALL LETTER B WITH LINE BELOW
    ('\u{1E08}', 'C'), // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
    ('\u{1E09}', 'c'), // LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
    ('\u{1E0A}', 'D'), // LATIN CAPITAL LETTER D WITH DOT ABOVE
    ('\u{1E0B}', 'd'), // LATIN SMALL LETTER D WITH DOT ABOVE
    ('\u{1E0C}', 'D'), // LATIN CAPITAL LETTER D WITH DOT BELOW
    ('\u{1E0D}', 'd'), // LATIN SMALL LETTER D WITH DOT BELOW
    ('\u{1E0E}', 'D'), // LATIN CAPITAL LETTER D WITH LINE BELOW
    ('\u{1E0F}', 'd'), // LATIN SMALL LETTER D WITH LINE BELOW
    ('\u{1E10}', 'D'), // LATIN CAPITAL LETTER D WITH CEDILLA
    ('\u{1E11}', 'd'), // LATIN SMALL LETTER D WITH CEDILLA
    ('\u{1E12}', 'D'), // LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
    ('\u{1E13}', 'd'), // LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
    ('\u{1E14}', 'E'), // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
    ('\u{1E15}', 'e'), // LATIN SMALL LETTER E WITH MACRON AND GRAVE
    ('\u{1E16}', 'E'), // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
    ('\u{1E17}', 'e'), // LATIN SMALL LETTER E WITH MACRON AND ACUTE
    ('\u{1E18}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
    ('\u{1E19}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
    ('\u{1E1A}', 'E'), // LATIN CAPITAL LETTER E WITH TILDE BELOW
    ('\u{1E1B}', 'e'), // LATIN SMALL LETTER E WITH TILDE BELOW
    ('\u{1E1C}', 'E'), // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
    ('\u{1E1D}', 'e'), // LATIN SMALL LETTER E WITH CEDILLA AND BREVE
    ('\u{1E1E}', 'F'), // LATIN CAPITAL LETTER F WITH DOT ABOVE
    ('\u{1E1F}', 'f'), // LATIN SMALL LETTER F WITH DOT ABOVE
    ('\u{1E20}', 'G'), // LATIN CAPITAL LETTER G WITH MACRON
    ('\u{1E21}', 'g'), // LATIN SMALL LETTER G WITH MACRON
    ('\u{1E22}', 'H'), // LATIN CAPITAL LETTER H WITH DOT ABOVE
    ('\u{1E23}', 'h'), // LATIN SMALL LETTER H WITH DOT ABOVE
    ('\u{1E24}', 'H'), // LATIN CAPITAL LETTER H WITH DOT BELOW
    ('\u{1E25}', 'h'), // LATIN SMALL LETTER H WITH DOT BELOW
    ('\u{1E26}', 'H'), // LATIN CAPITAL LETTER H WITH DIAERESIS
    ('\u{1E27}', 'h'), // LATIN SMALL LETTER H WITH DIAERESIS
    ('\u{1E28}', 'H'), // LATIN CAPITAL LETTER H WITH CEDILLA
    ('\u{1E29}', 'h'), // LATIN SMALL LETTER H WITH CEDILLA
    ('\u{1E2A}', 'H'), // LATIN CAPITAL LETTER H WITH BREVE BELOW
    ('\u{1E2B}', 'h'), // LATIN SMALL LETTER H WITH BREVE BELOW
    ('\u{1E2C}', 'I'), // LATIN CAPITAL LETTER I WITH TILDE BELOW
    ('\u{1E2D}', 'i'), // LATIN SMALL LETTER I WITH TILDE BELOW
    ('\u{1E2E}', 'I'), // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
    ('\u{1E2F}', 'i'), // LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
    ('\u{1E30}', 'K'), // LATIN CAPITAL LETTER K WITH ACUTE
    ('\u{1E31}', 'k'), // LATIN SMALL LETTER K WITH ACUTE
    ('\u{1E32}', 'K'), // LATIN CAPITAL LETTER K WITH DOT BELOW
    ('\u{1E33}', 'k'), // LATIN SMALL LETTER K WITH DOT BELOW
    ('\u{1E34}', 'K'), // LATIN CAPITAL LETTER K WITH LINE BELOW
    ('\u{1E35}', 'k'), // LATIN SMALL LETTER K WITH LINE BELOW
    ('\u{1E36}', 'L'), // LATIN CAPITAL LETTER L WITH DOT BELOW
    ('\u{1E37}', 'l'), // LATIN SMALL LETTER L WITH DOT BELOW
    ('\u{1E38}', 'L'), // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
    ('\u{1E39}', 'l'), // LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
    ('\u{1E3A}', 'L'), // LATIN CAPITAL LETTER L WITH LINE BELOW
    ('\u{1E3B}', 'l'), // LATIN SMALL LETTER L WITH LINE BELOW
    ('\u{1E3C}', 'L'), // LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
    ('\u{1E3D}', 'l'), // LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
    ('\u{1E3E}', 'M'), // LATIN CAPITAL LETTER M WITH ACUTE
    ('\u{1E3F}', 'm'), // LATIN SMALL LETTER M WITH ACUTE
    ('\u{1E40}', 'M'), // LATIN CAPITAL LETTER M WITH DOT ABOVE
    ('\u{1E41}', 'm'), // LATIN SMALL LETTER M WITH DOT ABOVE
    ('\u{1E42}', 'M'), // LATIN CAPITAL LETTER M WITH DOT BELOW
    ('\u{1E43}', 'm'), // LATIN SMALL LETTER M WITH DOT BELOW
    ('\u{1E44}', 'N'), // LATIN CAPITAL LETTER N WITH DOT ABOVE
    ('\u{1E45}', 'n'), // LATIN SMALL LETTER N WITH DOT ABOVE
    ('\u{1E46}', 'N'), // LATIN CAPITAL LETTER N WITH DOT BELOW
    ('\u{1E47}', 'n'), // LATIN SMALL LETTER N WITH DOT BELOW
    ('\u{1E48}', 'N'), // LATIN CAPITAL LETTER N WITH LINE BELOW
    ('\u{1E49}', 'n'), // LATIN SMALL LETTER N WITH LINE BELOW
    ('\u{1E4A}', 'N'), // LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
    ('\u{1E4B}', 'n'), // LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
    ('\u{1E4C}', 'O'), // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
    ('\u{1E4D}', 'o'), // LATIN SMALL LETTER O WITH TILDE AND ACUTE
    ('\u{1E4E}', 'O'), // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
    ('\u{1E4F}', 'o'), // LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
    ('\u{1E50}', 'O'), // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
    ('\u{1E51}', 'o'), // LATIN SMALL LETTER O WITH MACRON AND GRAVE
    ('\u{1E52}', 'O'), // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
    ('\u{1E53}', 'o'), // LATIN SMALL LETTER O WITH MACRON AND ACUTE
    ('\u{1E54}', 'P'), // LATIN CAPITAL LETTER P WITH ACUTE
    ('\u{1E55}', 'p'), // LATIN SMALL LETTER P WITH ACUTE
    ('\u{1E56}', 'P'), // LATIN CAPITAL LETTER P WITH DOT ABOVE
    ('\u{1E57}', 'p'), // LATIN SMALL LETTER P WITH DOT ABOVE
    ('\u{1E58}', 'R'), // LATIN CAPITAL LETTER R WITH DOT ABOVE
    ('\u{1E59}', 'r'), // LATIN SMALL LETTER R WITH DOT ABOVE
    ('\u{1E5A}', 'R'), // LATIN CAPITAL LETTER R WITH DOT BELOW
    ('\u{1E5B}', 'r'), // LATIN SMALL LETTER R WITH DOT BELOW
    ('\u{1E5C}', 'R'), // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
    ('\u{1E5D}', 'r'), // LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
    ('\u{1E5E}', 'R'), // LATIN CAPITAL LETTER R WITH LINE BELOW
    ('\u{1E5F}', 'r'), // LATIN SMALL LETTER R WITH LINE BELOW
    ('\u{1E60}', 'S'), // LATIN CAPITAL LETTER S WITH DOT ABOVE
    ('\u{1E61}', 's'), // LATIN SMALL LETTER S WITH DOT ABOVE
    ('\u{1E62}', 'S'), // LATIN CAPITAL LETTER S WITH DOT BELOW
    ('\u{1E63}', 's'), // LATIN SMALL LETTER S WITH DOT BELOW
    ('\u{1E64}', 'S'), // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
    ('\u{1E65}', 's'), // LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
    ('\u{1E66}', 'S'), // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
    ('\u{1E67}', 's'), // LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
    ('\u{1E68}', 'S'), // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1E69}', 's'), // LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1E6A}', 'T'), // LATIN CAPITAL LETTER T WITH DOT ABOVE
    ('\u{1E6B}', 't'), // LATIN SMALL LETTER T WITH DOT ABOVE
    ('\u{1E6C}', 'T'), // LATIN CAPITAL LETTER T WITH DOT BELOW
    ('\u{1E6D}', 't'), // LATIN SMALL LETTER T WITH DOT BELOW
    ('\u{1E6E}', 'T'), // LATIN CAPITAL LETTER T WITH LINE BELOW
    ('\u{1E6F}', 't'), // LATIN SMALL LETTER T WITH LINE BELOW
    ('\u{1E70}', 'T'), // LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
    ('\u{1E71}', 't'), // LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
    ('\u{1E72}', 'U'), // LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
    ('\u{1E73}', 'u'), // LATIN SMALL LETTER U WITH DIAERESIS BELOW
    ('\u{1E74}', 'U'), // LATIN CAPITAL LETTER U WITH TILDE BELOW
    ('\u{1E75}', 'u'), // LATIN SMALL LETTER U WITH TILDE BELOW
    ('\u{1E76}', 'U'), // LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
    ('\u{1E77}', 'u'), // LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
    ('\u{1E78}', 'U'), // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
    ('\u{1E79}', 'u'), // LATIN SMALL LETTER U WITH TILDE AND ACUTE
    ('\u{1E7A}', 'U'), // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
    ('\u{1E7B}', 'u'), // LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
    ('\u{1E7C}', 'V'), // LATIN CAPITAL LETTER V WITH TILDE
    ('\u{1E7D}', 'v'), // LATIN SMALL LETTER V WITH TILDE
    ('\u{1E7E}', 'V'), // LATIN CAPITAL LETTER V WITH DOT BELOW
    ('\u{1E7F}', 'v'), // LATIN SMALL LETTER V WITH DOT BELOW
    ('\u{1E80}', 'W'), // LATIN CAPITAL LETTER W WITH GRAVE
    ('\u{1E81}', 'w'), // LATIN SMALL LETTER W WITH GRAVE
    ('\u{1E82}', 'W'), // LATIN CAPITAL LETTER W WITH ACUTE
    ('\u{1E83}', 'w'), // LATIN SMALL LETTER W WITH ACUTE
    ('\u{1E84}', 'W'), // LATIN CAPITAL LETTER W WITH DIAERESIS
    ('\u{1E85}', 'w'), // LATIN SMALL LETTER W WITH DIAERESIS
    ('\u{1E86}', 'W'), // LATIN CAPITAL LETTER W WITH DOT ABOVE
    ('\u{1E87}', 'w'), // LATIN SMALL LETTER W WITH DOT ABOVE
    ('\u{1E88}', 'W'), // LATIN CAPITAL LETTER W WITH DOT BELOW
    ('\u{1E89}', 'w'), // LATIN SMALL LETTER W WITH DOT BELOW
    ('\u{1E8A}', 'X'), // LATIN CAPITAL LETTER X WITH DOT ABOVE
    ('\u{1E8B}', 'x'), // LATIN SMALL LETTER X WITH DOT ABOVE
    ('\u{1E8C}', 'X'), // LATIN CAPITAL LETTER X WITH DIAERESIS
    ('\u{1E8D}', 'x'), // LATIN SMALL LETTER X WITH DIAERESIS
    ('\u{1E8E}', 'Y'), // LATIN CAPITAL LETTER Y WITH DOT ABOVE
    ('\u{1E8F}', 'y'), // LATIN SMALL LETTER Y WITH DOT ABOVE
    ('\u{1E90}', 'Z'), // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
    ('\u{1E91}', 'z'), // LATIN SMALL LETTER Z WITH CIRCUMFLEX
    ('\u{1E92}', 'Z'), // LATIN CAPITAL LETTER Z WITH DOT BELOW
    ('\u{1E93}', 'z'), // LATIN SMALL LETTER Z WITH DOT BELOW
    ('\u{1E94}', 'Z'), // LATIN CAPITAL LETTER Z WITH LINE BELOW
    ('\u{1E95}', 'z'), // LATIN SMALL LETTER Z WITH LINE BELOW
    ('\u{1E96}', 'h'), // LATIN SMALL LETTER H WITH LINE BELOW
    ('\u{1E97}', 't'), // LATIN SMALL LETTER T WITH DIAERESIS
    ('\u{1E98}', 'w'), // LATIN SMALL LETTER W WITH RING ABOVE
    ('\u{1E99}', 'y'), // LATIN SMALL LETTER Y WITH RING ABOVE
    ('\u{1E9B}', 's'), // LATIN SMALL LETTER LONG S WITH DOT ABOVE
    ('\u{1EA0}', 'A'), // LATIN CAPITAL LETTER A WITH DOT BELOW
    ('\u{1EA1}', 'a'), // LATIN SMALL LETTER A WITH DOT BELOW
    ('\u{1EA2}', 'A'), // LATIN CAPITAL LETTER A WITH HOOK ABOVE
    ('\u{1EA3}', 'a'), // LATIN SMALL LETTER A WITH HOOK ABOVE
    ('\u{1EA4}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
    ('\u{1EA5}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
    ('\u{1EA6}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
    ('\u{1EA7}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
    ('\u{1EA8}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1EA9}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1EAA}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
    ('\u{1EAB}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
    ('\u{1EAC}', 'A'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1EAD}', 'a'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1EAE}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
    ('\u{1EAF}', 'a'), // LATIN SMALL LETTER A WITH BREVE AND ACUTE
    ('\u{1EB0}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
    ('\u{1EB1}', 'a'), // LATIN SMALL LETTER A WITH BREVE AND GRAVE
    ('\u{1EB2}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
    ('\u{1EB3}', 'a'), // LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
    ('\u{1EB4}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE AND TILDE
    ('\u{1EB5}', 'a'), // LATIN SMALL LETTER A WITH BREVE AND TILDE
    ('\u{1EB6}', 'A'), // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
    ('\u{1EB7}', 'a'), // LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
    ('\u{1EB8}', 'E'), // LATIN CAPITAL LETTER E WITH DOT BELOW
    ('\u{1EB9}', 'e'), // LATIN SMALL LETTER E WITH DOT BELOW
    ('\u{1EBA}', 'E'), // LATIN CAPITAL LETTER E WITH HOOK ABOVE
    ('\u{1EBB}', 'e'), // LATIN SMALL LETTER E WITH HOOK ABOVE
    ('\u{1EBC}', 'E'), // LATIN CAPITAL LETTER E WITH TILDE
    ('\u{1EBD}', 'e'), // LATIN SMALL LETTER E WITH TILDE
    ('\u{1EBE}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
    ('\u{1EBF}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
    ('\u{1EC0}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
    ('\u{1EC1}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
    ('\u{1EC2}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1EC3}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1EC4}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
    ('\u{1EC5}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
    ('\u{1EC6}', 'E'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1EC7}', 'e'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1EC8}', 'I'), // LATIN CAPITAL LETTER I WITH HOOK ABOVE
    ('\u{1EC9}', 'i'), // LATIN SMALL LETTER I WITH HOOK ABOVE
    ('\u{1ECA}', 'I'), // LATIN CAPITAL LETTER I WITH DOT BELOW
    ('\u{1ECB}', 'i'), // LATIN SMALL LETTER I WITH DOT BELOW
    ('\u{1ECC}', 'O'), // LATIN CAPITAL LETTER O WITH DOT BELOW
    ('\u{1ECD}', 'o'), // LATIN SMALL LETTER O WITH DOT BELOW
    ('\u{1ECE}', 'O'), // LATIN CAPITAL LETTER O WITH HOOK ABOVE
    ('\u{1ECF}', 'o'), // LATIN SMALL LETTER O WITH HOOK ABOVE
    ('\u{1ED0}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
    ('\u{1ED1}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
    ('\u{1ED2}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
    ('\u{1ED3}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
    ('\u{1ED4}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1ED5}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    ('\u{1ED6}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
    ('\u{1ED7}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
    ('\u{1ED8}', 'O'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1ED9}', 'o'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1EDA}', 'O'), // LATIN CAPITAL LETTER O WITH HORN AND ACUTE
    ('\u{1EDB}', 'o'), // LATIN SMALL LETTER O WITH HORN AND ACUTE
    ('\u{1EDC}', 'O'), // LATIN CAPITAL LETTER O WITH HORN AND GRAVE
    ('\u{1EDD}', 'o'), // LATIN SMALL LETTER O WITH HORN AND GRAVE
    ('\u{1EDE}', 'O'), // LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
    ('\u{1EDF}', 'o'), // LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
    ('\u{1EE0}', 'O'), // LATIN CAPITAL LETTER O WITH HORN AND TILDE
    ('\u{1EE1}', 'o'), // LATIN SMALL LETTER O WITH HORN AND TILDE
    ('\u{1EE2}', 'O'), // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
    ('\u{1EE3}', 'o'), // LATIN SMALL LETTER O WITH HORN AND DOT BELOW
    ('\u{1EE4}', 'U'), // LATIN CAPITAL LETTER U WITH DOT BELOW
    ('\u{1EE5}', 'u'), // LATIN SMALL LETTER U WITH DOT BELOW
    ('\u{1EE6}', 'U'), // LATIN CAPITAL LETTER U WITH HOOK ABOVE
    ('\u{1EE7}', 'u'), // LATIN SMALL LETTER U WITH HOOK ABOVE
    ('\u{1EE8}', 'U'), // LATIN CAPITAL LETTER U WITH HORN AND ACUTE
    ('\u{1EE9}', 'u'), // LATIN SMALL LETTER U WITH HORN AND ACUTE
    ('\u{1EEA}', 'U'), // LATIN CAPITAL LETTER U WITH HORN AND GRAVE
    ('\u{1EEB}', 'u'), // LATIN SMALL LETTER U WITH HORN AND GRAVE
    ('\u{1EEC}', 'U'), // LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
    ('\u{1EED}', 'u'), // LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
    ('\u{1EEE}', 'U'), // LATIN CAPITAL LETTER U WITH HORN AND TILDE
    ('\u{1EEF}', 'u'), // LATIN SMALL LETTER U WITH HORN AND TILDE
    ('\u{1EF0}', 'U'), // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
    ('\u{1EF1}', 'u'), // LATIN SMALL LETTER U WITH HORN AND DOT BELOW
    ('\u{1EF2}', 'Y'), // LATIN CAPITAL LETTER Y WITH GRAVE
    ('\u{1EF3}', 'y'), // LATIN SMALL LETTER Y WITH GRAVE
    ('\u{1EF4}', 'Y'), // LATIN CAPITAL LETTER Y WITH DOT BELOW
    ('\u{1EF5}', 'y'), // LATIN SMALL LETTER Y WITH DOT BELOW
    ('\u{1EF6}', 'Y'), // LATIN CAPITAL LETTER Y WITH HOOK ABOVE
    ('\u{1EF7}', 'y'), // LATIN SMALL LETTER Y WITH HOOK ABOVE
    ('\u{1EF8}', 'Y'), // LATIN CAPITAL LETTER Y WITH TILDE
    ('\u{1EF9}', 'y'), // LATIN SMALL LETTER Y WITH TILDE
    ('\u{1FEF}', '`'), // GREEK VARIA
    // ---- General punctuation / Letterlike ----
    ('\u{2024}', '.'), // ONE DOT LEADER
    ('\u{2070}', '0'), // SUPERSCRIPT ZERO
    ('\u{2071}', 'i'), // SUPERSCRIPT LATIN SMALL LETTER I
    ('\u{2074}', '4'), // SUPERSCRIPT FOUR
    ('\u{2075}', '5'), // SUPERSCRIPT FIVE
    ('\u{2076}', '6'), // SUPERSCRIPT SIX
    ('\u{2077}', '7'), // SUPERSCRIPT SEVEN
    ('\u{2078}', '8'), // SUPERSCRIPT EIGHT
    ('\u{2079}', '9'), // SUPERSCRIPT NINE
    ('\u{207A}', '+'), // SUPERSCRIPT PLUS SIGN
    ('\u{207C}', '='), // SUPERSCRIPT EQUALS SIGN
    ('\u{207D}', '('), // SUPERSCRIPT LEFT PARENTHESIS
    ('\u{207E}', ')'), // SUPERSCRIPT RIGHT PARENTHESIS
    ('\u{207F}', 'n'), // SUPERSCRIPT LATIN SMALL LETTER N
    ('\u{2080}', '0'), // SUBSCRIPT ZERO
    ('\u{2081}', '1'), // SUBSCRIPT ONE
    ('\u{2082}', '2'), // SUBSCRIPT TWO
    ('\u{2083}', '3'), // SUBSCRIPT THREE
    ('\u{2084}', '4'), // SUBSCRIPT FOUR
    ('\u{2085}', '5'), // SUBSCRIPT FIVE
    ('\u{2086}', '6'), // SUBSCRIPT SIX
    ('\u{2087}', '7'), // SUBSCRIPT SEVEN
    ('\u{2088}', '8'), // SUBSCRIPT EIGHT
    ('\u{2089}', '9'), // SUBSCRIPT NINE
    ('\u{208A}', '+'), // SUBSCRIPT PLUS SIGN
    ('\u{208C}', '='), // SUBSCRIPT EQUALS SIGN
    ('\u{208D}', '('), // SUBSCRIPT LEFT PARENTHESIS
    ('\u{208E}', ')'), // SUBSCRIPT RIGHT PARENTHESIS
    ('\u{2090}', 'a'), // LATIN SUBSCRIPT SMALL LETTER A
    ('\u{2091}', 'e'), // LATIN SUBSCRIPT SMALL LETTER E
    ('\u{2092}', 'o'), // LATIN SUBSCRIPT SMALL LETTER O
    ('\u{2093}', 'x'), // LATIN SUBSCRIPT SMALL LETTER X
    ('\u{2095}', 'h'), // LATIN SUBSCRIPT SMALL LETTER H
    ('\u{2096}', 'k'), // LATIN SUBSCRIPT SMALL LETTER K
    ('\u{2097}', 'l'), // LATIN SUBSCRIPT SMALL LETTER L
    ('\u{2098}', 'm'), // LATIN SUBSCRIPT SMALL LETTER M
    ('\u{2099}', 'n'), // LATIN SUBSCRIPT SMALL LETTER N
    ('\u{209A}', 'p'), // LATIN SUBSCRIPT SMALL LETTER P
    ('\u{209B}', 's'), // LATIN SUBSCRIPT SMALL LETTER S
    ('\u{209C}', 't'), // LATIN SUBSCRIPT SMALL LETTER T
    ('\u{2102}', 'C'), // DOUBLE-STRUCK CAPITAL C
    ('\u{210A}', 'g'), // SCRIPT SMALL G
    ('\u{210B}', 'H'), // SCRIPT CAPITAL H
    ('\u{210C}', 'H'), // BLACK-LETTER CAPITAL H
    ('\u{210D}', 'H'), // DOUBLE-STRUCK CAPITAL H
    ('\u{210E}', 'h'), // PLANCK CONSTANT
    ('\u{2110}', 'I'), // SCRIPT CAPITAL I
    ('\u{2111}', 'I'), // BLACK-LETTER CAPITAL I
    ('\u{2112}', 'L'), // SCRIPT CAPITAL L
    ('\u{2113}', 'l'), // SCRIPT SMALL L
    ('\u{2115}', 'N'), // DOUBLE-STRUCK CAPITAL N
    ('\u{2119}', 'P'), // DOUBLE-STRUCK CAPITAL P
    ('\u{211A}', 'Q'), // DOUBLE-STRUCK CAPITAL Q
    ('\u{211B}', 'R'), // SCRIPT CAPITAL R
    ('\u{211C}', 'R'), // BLACK-LETTER CAPITAL R
    ('\u{211D}', 'R'), // DOUBLE-STRUCK CAPITAL R
    ('\u{2124}', 'Z'), // DOUBLE-STRUCK CAPITAL Z
    ('\u{2128}', 'Z'), // BLACK-LETTER CAPITAL Z
    ('\u{212A}', 'K'), // KELVIN SIGN
    ('\u{212B}', 'A'), // ANGSTROM SIGN
    ('\u{212C}', 'B'), // SCRIPT CAPITAL B
    ('\u{212D}', 'C'), // BLACK-LETTER CAPITAL C
    ('\u{212F}', 'e'), // SCRIPT SMALL E
    ('\u{2130}', 'E'), // SCRIPT CAPITAL E
    ('\u{2131}', 'F'), // SCRIPT CAPITAL F
    ('\u{2133}', 'M'), // SCRIPT CAPITAL M
    ('\u{2134}', 'o'), // SCRIPT SMALL O
    ('\u{2139}', 'i'), // INFORMATION SOURCE
    ('\u{2145}', 'D'), // DOUBLE-STRUCK ITALIC CAPITAL D
    ('\u{2146}', 'd'), // DOUBLE-STRUCK ITALIC SMALL D
    ('\u{2147}', 'e'), // DOUBLE-STRUCK ITALIC SMALL E
    ('\u{2148}', 'i'), // DOUBLE-STRUCK ITALIC SMALL I
    ('\u{2149}', 'j'), // DOUBLE-STRUCK ITALIC SMALL J
    ('\u{2160}', 'I'), // ROMAN NUMERAL ONE
    ('\u{2164}', 'V'), // ROMAN NUMERAL FIVE
    ('\u{2169}', 'X'), // ROMAN NUMERAL TEN
    ('\u{216C}', 'L'), // ROMAN NUMERAL FIFTY
    ('\u{216D}', 'C'), // ROMAN NUMERAL ONE HUNDRED
    ('\u{216E}', 'D'), // ROMAN NUMERAL FIVE HUNDRED
    ('\u{216F}', 'M'), // ROMAN NUMERAL ONE THOUSAND
    ('\u{2170}', 'i'), // SMALL ROMAN NUMERAL ONE
    ('\u{2174}', 'v'), // SMALL ROMAN NUMERAL FIVE
    ('\u{2179}', 'x'), // SMALL ROMAN NUMERAL TEN
    ('\u{217C}', 'l'), // SMALL ROMAN NUMERAL FIFTY
    ('\u{217D}', 'c'), // SMALL ROMAN NUMERAL ONE HUNDRED
    ('\u{217E}', 'd'), // SMALL ROMAN NUMERAL FIVE HUNDRED
    ('\u{217F}', 'm'), // SMALL ROMAN NUMERAL ONE THOUSAND
    // ---- Mathematical / Enclosed ----
    ('\u{2260}', '='), // NOT EQUAL TO
    ('\u{226E}', '<'), // NOT LESS-THAN
    ('\u{226F}', '>'), // NOT GREATER-THAN
    ('\u{2460}', '1'), // CIRCLED DIGIT ONE
    ('\u{2461}', '2'), // CIRCLED DIGIT TWO
    ('\u{2462}', '3'), // CIRCLED DIGIT THREE
    ('\u{2463}', '4'), // CIRCLED DIGIT FOUR
    ('\u{2464}', '5'), // CIRCLED DIGIT FIVE
    ('\u{2465}', '6'), // CIRCLED DIGIT SIX
    ('\u{2466}', '7'), // CIRCLED DIGIT SEVEN
    ('\u{2467}', '8'), // CIRCLED DIGIT EIGHT
    ('\u{2468}', '9'), // CIRCLED DIGIT NINE
    ('\u{24B6}', 'A'), // CIRCLED LATIN CAPITAL LETTER A
    ('\u{24B7}', 'B'), // CIRCLED LATIN CAPITAL LETTER B
    ('\u{24B8}', 'C'), // CIRCLED LATIN CAPITAL LETTER C
    ('\u{24B9}', 'D'), // CIRCLED LATIN CAPITAL LETTER D
    ('\u{24BA}', 'E'), // CIRCLED LATIN CAPITAL LETTER E
    ('\u{24BB}', 'F'), // CIRCLED LATIN CAPITAL LETTER F
    ('\u{24BC}', 'G'), // CIRCLED LATIN CAPITAL LETTER G
    ('\u{24BD}', 'H'), // CIRCLED LATIN CAPITAL LETTER H
    ('\u{24BE}', 'I'), // CIRCLED LATIN CAPITAL LETTER I
    ('\u{24BF}', 'J'), // CIRCLED LATIN CAPITAL LETTER J
    ('\u{24C0}', 'K'), // CIRCLED LATIN CAPITAL LETTER K
    ('\u{24C1}', 'L'), // CIRCLED LATIN CAPITAL LETTER L
    ('\u{24C2}', 'M'), // CIRCLED LATIN CAPITAL LETTER M
    ('\u{24C3}', 'N'), // CIRCLED LATIN CAPITAL LETTER N
    ('\u{24C4}', 'O'), // CIRCLED LATIN CAPITAL LETTER O
    ('\u{24C5}', 'P'), // CIRCLED LATIN CAPITAL LETTER P
    ('\u{24C6}', 'Q'), // CIRCLED LATIN CAPITAL LETTER Q
    ('\u{24C7}', 'R'), // CIRCLED LATIN CAPITAL LETTER R
    ('\u{24C8}', 'S'), // CIRCLED LATIN CAPITAL LETTER S
    ('\u{24C9}', 'T'), // CIRCLED LATIN CAPITAL LETTER T
    ('\u{24CA}', 'U'), // CIRCLED LATIN CAPITAL LETTER U
    ('\u{24CB}', 'V'), // CIRCLED LATIN CAPITAL LETTER V
    ('\u{24CC}', 'W'), // CIRCLED LATIN CAPITAL LETTER W
    ('\u{24CD}', 'X'), // CIRCLED LATIN CAPITAL LETTER X
    ('\u{24CE}', 'Y'), // CIRCLED LATIN CAPITAL LETTER Y
    ('\u{24CF}', 'Z'), // CIRCLED LATIN CAPITAL LETTER Z
    ('\u{24D0}', 'a'), // CIRCLED LATIN SMALL LETTER A
    ('\u{24D1}', 'b'), // CIRCLED LATIN SMALL LETTER B
    ('\u{24D2}', 'c'), // CIRCLED LATIN SMALL LETTER C
    ('\u{24D3}', 'd'), // CIRCLED LATIN SMALL LETTER D
    ('\u{24D4}', 'e'), // CIRCLED LATIN SMALL LETTER E
    ('\u{24D5}', 'f'), // CIRCLED LATIN SMALL LETTER F
    ('\u{24D6}', 'g'), // CIRCLED LATIN SMALL LETTER G
    ('\u{24D7}', 'h'), // CIRCLED LATIN SMALL LETTER H
    ('\u{24D8}', 'i'), // CIRCLED LATIN SMALL LETTER I
    ('\u{24D9}', 'j'), // CIRCLED LATIN SMALL LETTER J
    ('\u{24DA}', 'k'), // CIRCLED LATIN SMALL LETTER K
    ('\u{24DB}', 'l'), // CIRCLED LATIN SMALL LETTER L
    ('\u{24DC}', 'm'), // CIRCLED LATIN SMALL LETTER M
    ('\u{24DD}', 'n'), // CIRCLED LATIN SMALL LETTER N
    ('\u{24DE}', 'o'), // CIRCLED LATIN SMALL LETTER O
    ('\u{24DF}', 'p'), // CIRCLED LATIN SMALL LETTER P
    ('\u{24E0}', 'q'), // CIRCLED LATIN SMALL LETTER Q
    ('\u{24E1}', 'r'), // CIRCLED LATIN SMALL LETTER R
    ('\u{24E2}', 's'), // CIRCLED LATIN SMALL LETTER S
    ('\u{24E3}', 't'), // CIRCLED LATIN SMALL LETTER T
    ('\u{24E4}', 'u'), // CIRCLED LATIN SMALL LETTER U
    ('\u{24E5}', 'v'), // CIRCLED LATIN SMALL LETTER V
    ('\u{24E6}', 'w'), // CIRCLED LATIN SMALL LETTER W
    ('\u{24E7}', 'x'), // CIRCLED LATIN SMALL LETTER X
    ('\u{24E8}', 'y'), // CIRCLED LATIN SMALL LETTER Y
    ('\u{24E9}', 'z'), // CIRCLED LATIN SMALL LETTER Z
    ('\u{24EA}', '0'), // CIRCLED DIGIT ZERO
    // ---- Box drawing / CJK ----
    ('\u{2C7C}', 'j'), // LATIN SUBSCRIPT SMALL LETTER J
    ('\u{2C7D}', 'V'), // MODIFIER LETTER CAPITAL V
    // ---- CJK / Compatibility ----
    ('\u{A7F2}', 'C'), // MODIFIER LETTER CAPITAL C
    ('\u{A7F3}', 'F'), // MODIFIER LETTER CAPITAL F
    ('\u{A7F4}', 'Q'), // MODIFIER LETTER CAPITAL Q
    // ---- Presentation forms ----
    ('\u{FB29}', '+'), // HEBREW LETTER ALTERNATIVE PLUS SIGN
    ('\u{FE10}', ','), // PRESENTATION FORM FOR VERTICAL COMMA
    ('\u{FE13}', ':'), // PRESENTATION FORM FOR VERTICAL COLON
    ('\u{FE14}', ';'), // PRESENTATION FORM FOR VERTICAL SEMICOLON
    ('\u{FE15}', '!'), // PRESENTATION FORM FOR VERTICAL EXCLAMATION MARK
    ('\u{FE16}', '?'), // PRESENTATION FORM FOR VERTICAL QUESTION MARK
    ('\u{FE33}', '_'), // PRESENTATION FORM FOR VERTICAL LOW LINE
    ('\u{FE34}', '_'), // PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
    ('\u{FE35}', '('), // PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS
    ('\u{FE36}', ')'), // PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS
    ('\u{FE37}', '{'), // PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET
    ('\u{FE38}', '}'), // PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET
    ('\u{FE47}', '['), // PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET
    ('\u{FE48}', ']'), // PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET
    ('\u{FE4D}', '_'), // DASHED LOW LINE
    ('\u{FE4E}', '_'), // CENTRELINE LOW LINE
    ('\u{FE4F}', '_'), // WAVY LOW LINE
    ('\u{FE50}', ','), // SMALL COMMA
    ('\u{FE52}', '.'), // SMALL FULL STOP
    ('\u{FE54}', ';'), // SMALL SEMICOLON
    ('\u{FE55}', ':'), // SMALL COLON
    ('\u{FE56}', '?'), // SMALL QUESTION MARK
    ('\u{FE57}', '!'), // SMALL EXCLAMATION MARK
    ('\u{FE59}', '('), // SMALL LEFT PARENTHESIS
    ('\u{FE5A}', ')'), // SMALL RIGHT PARENTHESIS
    ('\u{FE5B}', '{'), // SMALL LEFT CURLY BRACKET
    ('\u{FE5C}', '}'), // SMALL RIGHT CURLY BRACKET
    ('\u{FE5F}', '#'), // SMALL NUMBER SIGN
    ('\u{FE60}', '&'), // SMALL AMPERSAND
    ('\u{FE61}', '*'), // SMALL ASTERISK
    ('\u{FE62}', '+'), // SMALL PLUS SIGN
    ('\u{FE63}', '-'), // SMALL HYPHEN-MINUS
    ('\u{FE64}', '<'), // SMALL LESS-THAN SIGN
    ('\u{FE65}', '>'), // SMALL GREATER-THAN SIGN
    ('\u{FE66}', '='), // SMALL EQUALS SIGN
    ('\u{FE68}', '\\'), // SMALL REVERSE SOLIDUS
    ('\u{FE69}', '$'), // SMALL DOLLAR SIGN
    ('\u{FE6A}', '%'), // SMALL PERCENT SIGN
    ('\u{FE6B}', '@'), // SMALL COMMERCIAL AT
    // ---- Halfwidth / Fullwidth ----
    ('\u{FF01}', '!'), // FULLWIDTH EXCLAMATION MARK
    ('\u{FF02}', '"'), // FULLWIDTH QUOTATION MARK
    ('\u{FF03}', '#'), // FULLWIDTH NUMBER SIGN
    ('\u{FF04}', '$'), // FULLWIDTH DOLLAR SIGN
    ('\u{FF05}', '%'), // FULLWIDTH PERCENT SIGN
    ('\u{FF06}', '&'), // FULLWIDTH AMPERSAND
    ('\u{FF07}', '\''), // FULLWIDTH APOSTROPHE
    ('\u{FF08}', '('), // FULLWIDTH LEFT PARENTHESIS
    ('\u{FF09}', ')'), // FULLWIDTH RIGHT PARENTHESIS
    ('\u{FF0A}', '*'), // FULLWIDTH ASTERISK
    ('\u{FF0B}', '+'), // FULLWIDTH PLUS SIGN
    ('\u{FF0C}', ','), // FULLWIDTH COMMA
    ('\u{FF0D}', '-'), // FULLWIDTH HYPHEN-MINUS
    ('\u{FF0E}', '.'), // FULLWIDTH FULL STOP
    ('\u{FF0F}', '/'), // FULLWIDTH SOLIDUS
    ('\u{FF10}', '0'), // FULLWIDTH DIGIT ZERO
    ('\u{FF11}', '1'), // FULLWIDTH DIGIT ONE
    ('\u{FF12}', '2'), // FULLWIDTH DIGIT TWO
    ('\u{FF13}', '3'), // FULLWIDTH DIGIT THREE
    ('\u{FF14}', '4'), // FULLWIDTH DIGIT FOUR
    ('\u{FF15}', '5'), // FULLWIDTH DIGIT FIVE
    ('\u{FF16}', '6'), // FULLWIDTH DIGIT SIX
    ('\u{FF17}', '7'), // FULLWIDTH DIGIT SEVEN
    ('\u{FF18}', '8'), // FULLWIDTH DIGIT EIGHT
    ('\u{FF19}', '9'), // FULLWIDTH DIGIT NINE
    ('\u{FF1A}', ':'), // FULLWIDTH COLON
    ('\u{FF1B}', ';'), // FULLWIDTH SEMICOLON
    ('\u{FF1C}', '<'), // FULLWIDTH LESS-THAN SIGN
    ('\u{FF1D}', '='), // FULLWIDTH EQUALS SIGN
    ('\u{FF1E}', '>'), // FULLWIDTH GREATER-THAN SIGN
    ('\u{FF1F}', '?'), // FULLWIDTH QUESTION MARK
    ('\u{FF20}', '@'), // FULLWIDTH COMMERCIAL AT
    ('\u{FF21}', 'A'), // FULLWIDTH LATIN CAPITAL LETTER A
    ('\u{FF22}', 'B'), // FULLWIDTH LATIN CAPITAL LETTER B
    ('\u{FF23}', 'C'), // FULLWIDTH LATIN CAPITAL LETTER C
    ('\u{FF24}', 'D'), // FULLWIDTH LATIN CAPITAL LETTER D
    ('\u{FF25}', 'E'), // FULLWIDTH LATIN CAPITAL LETTER E
    ('\u{FF26}', 'F'), // FULLWIDTH LATIN CAPITAL LETTER F
    ('\u{FF27}', 'G'), // FULLWIDTH LATIN CAPITAL LETTER G
    ('\u{FF28}', 'H'), // FULLWIDTH LATIN CAPITAL LETTER H
    ('\u{FF29}', 'I'), // FULLWIDTH LATIN CAPITAL LETTER I
    ('\u{FF2A}', 'J'), // FULLWIDTH LATIN CAPITAL LETTER J
    ('\u{FF2B}', 'K'), // FULLWIDTH LATIN CAPITAL LETTER K
    ('\u{FF2C}', 'L'), // FULLWIDTH LATIN CAPITAL LETTER L
    ('\u{FF2D}', 'M'), // FULLWIDTH LATIN CAPITAL LETTER M
    ('\u{FF2E}', 'N'), // FULLWIDTH LATIN CAPITAL LETTER N
    ('\u{FF2F}', 'O'), // FULLWIDTH LATIN CAPITAL LETTER O
    ('\u{FF30}', 'P'), // FULLWIDTH LATIN CAPITAL LETTER P
    ('\u{FF31}', 'Q'), // FULLWIDTH LATIN CAPITAL LETTER Q
    ('\u{FF32}', 'R'), // FULLWIDTH LATIN CAPITAL LETTER R
    ('\u{FF33}', 'S'), // FULLWIDTH LATIN CAPITAL LETTER S
    ('\u{FF34}', 'T'), // FULLWIDTH LATIN CAPITAL LETTER T
    ('\u{FF35}', 'U'), // FULLWIDTH LATIN CAPITAL LETTER U
    ('\u{FF36}', 'V'), // FULLWIDTH LATIN CAPITAL LETTER V
    ('\u{FF37}', 'W'), // FULLWIDTH LATIN CAPITAL LETTER W
    ('\u{FF38}', 'X'), // FULLWIDTH LATIN CAPITAL LETTER X
    ('\u{FF39}', 'Y'), // FULLWIDTH LATIN CAPITAL LETTER Y
    ('\u{FF3A}', 'Z'), // FULLWIDTH LATIN CAPITAL LETTER Z
    ('\u{FF3B}', '['), // FULLWIDTH LEFT SQUARE BRACKET
    ('\u{FF3C}', '\\'), // FULLWIDTH REVERSE SOLIDUS
    ('\u{FF3D}', ']'), // FULLWIDTH RIGHT SQUARE BRACKET
    ('\u{FF3E}', '^'), // FULLWIDTH CIRCUMFLEX ACCENT
    ('\u{FF3F}', '_'), // FULLWIDTH LOW LINE
    ('\u{FF40}', '`'), // FULLWIDTH GRAVE ACCENT
    ('\u{FF41}', 'a'), // FULLWIDTH LATIN SMALL LETTER A
    ('\u{FF42}', 'b'), // FULLWIDTH LATIN SMALL LETTER B
    ('\u{FF43}', 'c'), // FULLWIDTH LATIN SMALL LETTER C
    ('\u{FF44}', 'd'), // FULLWIDTH LATIN SMALL LETTER D
    ('\u{FF45}', 'e'), // FULLWIDTH LATIN SMALL LETTER E
    ('\u{FF46}', 'f'), // FULLWIDTH LATIN SMALL LETTER F
    ('\u{FF47}', 'g'), // FULLWIDTH LATIN SMALL LETTER G
    ('\u{FF48}', 'h'), // FULLWIDTH LATIN SMALL LETTER H
    ('\u{FF49}', 'i'), // FULLWIDTH LATIN SMALL LETTER I
    ('\u{FF4A}', 'j'), // FULLWIDTH LATIN SMALL LETTER J
    ('\u{FF4B}', 'k'), // FULLWIDTH LATIN SMALL LETTER K
    ('\u{FF4C}', 'l'), // FULLWIDTH LATIN SMALL LETTER L
    ('\u{FF4D}', 'm'), // FULLWIDTH LATIN SMALL LETTER M
    ('\u{FF4E}', 'n'), // FULLWIDTH LATIN SMALL LETTER N
    ('\u{FF4F}', 'o'), // FULLWIDTH LATIN SMALL LETTER O
    ('\u{FF50}', 'p'), // FULLWIDTH LATIN SMALL LETTER P
    ('\u{FF51}', 'q'), // FULLWIDTH LATIN SMALL LETTER Q
    ('\u{FF52}', 'r'), // FULLWIDTH LATIN SMALL LETTER R
    ('\u{FF53}', 's'), // FULLWIDTH LATIN SMALL LETTER S
    ('\u{FF54}', 't'), // FULLWIDTH LATIN SMALL LETTER T
    ('\u{FF55}', 'u'), // FULLWIDTH LATIN SMALL LETTER U
    ('\u{FF56}', 'v'), // FULLWIDTH LATIN SMALL LETTER V
    ('\u{FF57}', 'w'), // FULLWIDTH LATIN SMALL LETTER W
    ('\u{FF58}', 'x'), // FULLWIDTH LATIN SMALL LETTER X
    ('\u{FF59}', 'y'), // FULLWIDTH LATIN SMALL LETTER Y
    ('\u{FF5A}', 'z'), // FULLWIDTH LATIN SMALL LETTER Z
    ('\u{FF5B}', '{'), // FULLWIDTH LEFT CURLY BRACKET
    ('\u{FF5C}', '|'), // FULLWIDTH VERTICAL LINE
    ('\u{FF5D}', '}'), // FULLWIDTH RIGHT CURLY BRACKET
    ('\u{FF5E}', '~'), // FULLWIDTH TILDE
    // ---- Supplementary (Mathematical Alphanumeric etc.) ----
    ('\u{107A5}', 'q'), // MODIFIER LETTER SMALL Q
    ('\u{1D400}', 'A'), // MATHEMATICAL BOLD CAPITAL A
    ('\u{1D401}', 'B'), // MATHEMATICAL BOLD CAPITAL B
    ('\u{1D402}', 'C'), // MATHEMATICAL BOLD CAPITAL C
    ('\u{1D403}', 'D'), // MATHEMATICAL BOLD CAPITAL D
    ('\u{1D404}', 'E'), // MATHEMATICAL BOLD CAPITAL E
    ('\u{1D405}', 'F'), // MATHEMATICAL BOLD CAPITAL F
    ('\u{1D406}', 'G'), // MATHEMATICAL BOLD CAPITAL G
    ('\u{1D407}', 'H'), // MATHEMATICAL BOLD CAPITAL H
    ('\u{1D408}', 'I'), // MATHEMATICAL BOLD CAPITAL I
    ('\u{1D409}', 'J'), // MATHEMATICAL BOLD CAPITAL J
    ('\u{1D40A}', 'K'), // MATHEMATICAL BOLD CAPITAL K
    ('\u{1D40B}', 'L'), // MATHEMATICAL BOLD CAPITAL L
    ('\u{1D40C}', 'M'), // MATHEMATICAL BOLD CAPITAL M
    ('\u{1D40D}', 'N'), // MATHEMATICAL BOLD CAPITAL N
    ('\u{1D40E}', 'O'), // MATHEMATICAL BOLD CAPITAL O
    ('\u{1D40F}', 'P'), // MATHEMATICAL BOLD CAPITAL P
    ('\u{1D410}', 'Q'), // MATHEMATICAL BOLD CAPITAL Q
    ('\u{1D411}', 'R'), // MATHEMATICAL BOLD CAPITAL R
    ('\u{1D412}', 'S'), // MATHEMATICAL BOLD CAPITAL S
    ('\u{1D413}', 'T'), // MATHEMATICAL BOLD CAPITAL T
    ('\u{1D414}', 'U'), // MATHEMATICAL BOLD CAPITAL U
    ('\u{1D415}', 'V'), // MATHEMATICAL BOLD CAPITAL V
    ('\u{1D416}', 'W'), // MATHEMATICAL BOLD CAPITAL W
    ('\u{1D417}', 'X'), // MATHEMATICAL BOLD CAPITAL X
    ('\u{1D418}', 'Y'), // MATHEMATICAL BOLD CAPITAL Y
    ('\u{1D419}', 'Z'), // MATHEMATICAL BOLD CAPITAL Z
    ('\u{1D41A}', 'a'), // MATHEMATICAL BOLD SMALL A
    ('\u{1D41B}', 'b'), // MATHEMATICAL BOLD SMALL B
    ('\u{1D41C}', 'c'), // MATHEMATICAL BOLD SMALL C
    ('\u{1D41D}', 'd'), // MATHEMATICAL BOLD SMALL D
    ('\u{1D41E}', 'e'), // MATHEMATICAL BOLD SMALL E
    ('\u{1D41F}', 'f'), // MATHEMATICAL BOLD SMALL F
    ('\u{1D420}', 'g'), // MATHEMATICAL BOLD SMALL G
    ('\u{1D421}', 'h'), // MATHEMATICAL BOLD SMALL H
    ('\u{1D422}', 'i'), // MATHEMATICAL BOLD SMALL I
    ('\u{1D423}', 'j'), // MATHEMATICAL BOLD SMALL J
    ('\u{1D424}', 'k'), // MATHEMATICAL BOLD SMALL K
    ('\u{1D425}', 'l'), // MATHEMATICAL BOLD SMALL L
    ('\u{1D426}', 'm'), // MATHEMATICAL BOLD SMALL M
    ('\u{1D427}', 'n'), // MATHEMATICAL BOLD SMALL N
    ('\u{1D428}', 'o'), // MATHEMATICAL BOLD SMALL O
    ('\u{1D429}', 'p'), // MATHEMATICAL BOLD SMALL P
    ('\u{1D42A}', 'q'), // MATHEMATICAL BOLD SMALL Q
    ('\u{1D42B}', 'r'), // MATHEMATICAL BOLD SMALL R
    ('\u{1D42C}', 's'), // MATHEMATICAL BOLD SMALL S
    ('\u{1D42D}', 't'), // MATHEMATICAL BOLD SMALL T
    ('\u{1D42E}', 'u'), // MATHEMATICAL BOLD SMALL U
    ('\u{1D42F}', 'v'), // MATHEMATICAL BOLD SMALL V
    ('\u{1D430}', 'w'), // MATHEMATICAL BOLD SMALL W
    ('\u{1D431}', 'x'), // MATHEMATICAL BOLD SMALL X
    ('\u{1D432}', 'y'), // MATHEMATICAL BOLD SMALL Y
    ('\u{1D433}', 'z'), // MATHEMATICAL BOLD SMALL Z
    ('\u{1D434}', 'A'), // MATHEMATICAL ITALIC CAPITAL A
    ('\u{1D435}', 'B'), // MATHEMATICAL ITALIC CAPITAL B
    ('\u{1D436}', 'C'), // MATHEMATICAL ITALIC CAPITAL C
    ('\u{1D437}', 'D'), // MATHEMATICAL ITALIC CAPITAL D
    ('\u{1D438}', 'E'), // MATHEMATICAL ITALIC CAPITAL E
    ('\u{1D439}', 'F'), // MATHEMATICAL ITALIC CAPITAL F
    ('\u{1D43A}', 'G'), // MATHEMATICAL ITALIC CAPITAL G
    ('\u{1D43B}', 'H'), // MATHEMATICAL ITALIC CAPITAL H
    ('\u{1D43C}', 'I'), // MATHEMATICAL ITALIC CAPITAL I
    ('\u{1D43D}', 'J'), // MATHEMATICAL ITALIC CAPITAL J
    ('\u{1D43E}', 'K'), // MATHEMATICAL ITALIC CAPITAL K
    ('\u{1D43F}', 'L'), // MATHEMATICAL ITALIC CAPITAL L
    ('\u{1D440}', 'M'), // MATHEMATICAL ITALIC CAPITAL M
    ('\u{1D441}', 'N'), // MATHEMATICAL ITALIC CAPITAL N
    ('\u{1D442}', 'O'), // MATHEMATICAL ITALIC CAPITAL O
    ('\u{1D443}', 'P'), // MATHEMATICAL ITALIC CAPITAL P
    ('\u{1D444}', 'Q'), // MATHEMATICAL ITALIC CAPITAL Q
    ('\u{1D445}', 'R'), // MATHEMATICAL ITALIC CAPITAL R
    ('\u{1D446}', 'S'), // MATHEMATICAL ITALIC CAPITAL S
    ('\u{1D447}', 'T'), // MATHEMATICAL ITALIC CAPITAL T
    ('\u{1D448}', 'U'), // MATHEMATICAL ITALIC CAPITAL U
    ('\u{1D449}', 'V'), // MATHEMATICAL ITALIC CAPITAL V
    ('\u{1D44A}', 'W'), // MATHEMATICAL ITALIC CAPITAL W
    ('\u{1D44B}', 'X'), // MATHEMATICAL ITALIC CAPITAL X
    ('\u{1D44C}', 'Y'), // MATHEMATICAL ITALIC CAPITAL Y
    ('\u{1D44D}', 'Z'), // MATHEMATICAL ITALIC CAPITAL Z
    ('\u{1D44E}', 'a'), // MATHEMATICAL ITALIC SMALL A
    ('\u{1D44F}', 'b'), // MATHEMATICAL ITALIC SMALL B
    ('\u{1D450}', 'c'), // MATHEMATICAL ITALIC SMALL C
    ('\u{1D451}', 'd'), // MATHEMATICAL ITALIC SMALL D
    ('\u{1D452}', 'e'), // MATHEMATICAL ITALIC SMALL E
    ('\u{1D453}', 'f'), // MATHEMATICAL ITALIC SMALL F
    ('\u{1D454}', 'g'), // MATHEMATICAL ITALIC SMALL G
    ('\u{1D456}', 'i'), // MATHEMATICAL ITALIC SMALL I
    ('\u{1D457}', 'j'), // MATHEMATICAL ITALIC SMALL J
    ('\u{1D458}', 'k'), // MATHEMATICAL ITALIC SMALL K
    ('\u{1D459}', 'l'), // MATHEMATICAL ITALIC SMALL L
    ('\u{1D45A}', 'm'), // MATHEMATICAL ITALIC SMALL M
    ('\u{1D45B}', 'n'), // MATHEMATICAL ITALIC SMALL N
    ('\u{1D45C}', 'o'), // MATHEMATICAL ITALIC SMALL O
    ('\u{1D45D}', 'p'), // MATHEMATICAL ITALIC SMALL P
    ('\u{1D45E}', 'q'), // MATHEMATICAL ITALIC SMALL Q
    ('\u{1D45F}', 'r'), // MATHEMATICAL ITALIC SMALL R
    ('\u{1D460}', 's'), // MATHEMATICAL ITALIC SMALL S
    ('\u{1D461}', 't'), // MATHEMATICAL ITALIC SMALL T
    ('\u{1D462}', 'u'), // MATHEMATICAL ITALIC SMALL U
    ('\u{1D463}', 'v'), // MATHEMATICAL ITALIC SMALL V
    ('\u{1D464}', 'w'), // MATHEMATICAL ITALIC SMALL W
    ('\u{1D465}', 'x'), // MATHEMATICAL ITALIC SMALL X
    ('\u{1D466}', 'y'), // MATHEMATICAL ITALIC SMALL Y
    ('\u{1D467}', 'z'), // MATHEMATICAL ITALIC SMALL Z
    ('\u{1D468}', 'A'), // MATHEMATICAL BOLD ITALIC CAPITAL A
    ('\u{1D469}', 'B'), // MATHEMATICAL BOLD ITALIC CAPITAL B
    ('\u{1D46A}', 'C'), // MATHEMATICAL BOLD ITALIC CAPITAL C
    ('\u{1D46B}', 'D'), // MATHEMATICAL BOLD ITALIC CAPITAL D
    ('\u{1D46C}', 'E'), // MATHEMATICAL BOLD ITALIC CAPITAL E
    ('\u{1D46D}', 'F'), // MATHEMATICAL BOLD ITALIC CAPITAL F
    ('\u{1D46E}', 'G'), // MATHEMATICAL BOLD ITALIC CAPITAL G
    ('\u{1D46F}', 'H'), // MATHEMATICAL BOLD ITALIC CAPITAL H
    ('\u{1D470}', 'I'), // MATHEMATICAL BOLD ITALIC CAPITAL I
    ('\u{1D471}', 'J'), // MATHEMATICAL BOLD ITALIC CAPITAL J
    ('\u{1D472}', 'K'), // MATHEMATICAL BOLD ITALIC CAPITAL K
    ('\u{1D473}', 'L'), // MATHEMATICAL BOLD ITALIC CAPITAL L
    ('\u{1D474}', 'M'), // MATHEMATICAL BOLD ITALIC CAPITAL M
    ('\u{1D475}', 'N'), // MATHEMATICAL BOLD ITALIC CAPITAL N
    ('\u{1D476}', 'O'), // MATHEMATICAL BOLD ITALIC CAPITAL O
    ('\u{1D477}', 'P'), // MATHEMATICAL BOLD ITALIC CAPITAL P
    ('\u{1D478}', 'Q'), // MATHEMATICAL BOLD ITALIC CAPITAL Q
    ('\u{1D479}', 'R'), // MATHEMATICAL BOLD ITALIC CAPITAL R
    ('\u{1D47A}', 'S'), // MATHEMATICAL BOLD ITALIC CAPITAL S
    ('\u{1D47B}', 'T'), // MATHEMATICAL BOLD ITALIC CAPITAL T
    ('\u{1D47C}', 'U'), // MATHEMATICAL BOLD ITALIC CAPITAL U
    ('\u{1D47D}', 'V'), // MATHEMATICAL BOLD ITALIC CAPITAL V
    ('\u{1D47E}', 'W'), // MATHEMATICAL BOLD ITALIC CAPITAL W
    ('\u{1D47F}', 'X'), // MATHEMATICAL BOLD ITALIC CAPITAL X
    ('\u{1D480}', 'Y'), // MATHEMATICAL BOLD ITALIC CAPITAL Y
    ('\u{1D481}', 'Z'), // MATHEMATICAL BOLD ITALIC CAPITAL Z
    ('\u{1D482}', 'a'), // MATHEMATICAL BOLD ITALIC SMALL A
    ('\u{1D483}', 'b'), // MATHEMATICAL BOLD ITALIC SMALL B
    ('\u{1D484}', 'c'), // MATHEMATICAL BOLD ITALIC SMALL C
    ('\u{1D485}', 'd'), // MATHEMATICAL BOLD ITALIC SMALL D
    ('\u{1D486}', 'e'), // MATHEMATICAL BOLD ITALIC SMALL E
    ('\u{1D487}', 'f'), // MATHEMATICAL BOLD ITALIC SMALL F
    ('\u{1D488}', 'g'), // MATHEMATICAL BOLD ITALIC SMALL G
    ('\u{1D489}', 'h'), // MATHEMATICAL BOLD ITALIC SMALL H
    ('\u{1D48A}', 'i'), // MATHEMATICAL BOLD ITALIC SMALL I
    ('\u{1D48B}', 'j'), // MATHEMATICAL BOLD ITALIC SMALL J
    ('\u{1D48C}', 'k'), // MATHEMATICAL BOLD ITALIC SMALL K
    ('\u{1D48D}', 'l'), // MATHEMATICAL BOLD ITALIC SMALL L
    ('\u{1D48E}', 'm'), // MATHEMATICAL BOLD ITALIC SMALL M
    ('\u{1D48F}', 'n'), // MATHEMATICAL BOLD ITALIC SMALL N
    ('\u{1D490}', 'o'), // MATHEMATICAL BOLD ITALIC SMALL O
    ('\u{1D491}', 'p'), // MATHEMATICAL BOLD ITALIC SMALL P
    ('\u{1D492}', 'q'), // MATHEMATICAL BOLD ITALIC SMALL Q
    ('\u{1D493}', 'r'), // MATHEMATICAL BOLD ITALIC SMALL R
    ('\u{1D494}', 's'), // MATHEMATICAL BOLD ITALIC SMALL S
    ('\u{1D495}', 't'), // MATHEMATICAL BOLD ITALIC SMALL T
    ('\u{1D496}', 'u'), // MATHEMATICAL BOLD ITALIC SMALL U
    ('\u{1D497}', 'v'), // MATHEMATICAL BOLD ITALIC SMALL V
    ('\u{1D498}', 'w'), // MATHEMATICAL BOLD ITALIC SMALL W
    ('\u{1D499}', 'x'), // MATHEMATICAL BOLD ITALIC SMALL X
    ('\u{1D49A}', 'y'), // MATHEMATICAL BOLD ITALIC SMALL Y
    ('\u{1D49B}', 'z'), // MATHEMATICAL BOLD ITALIC SMALL Z
    ('\u{1D49C}', 'A'), // MATHEMATICAL SCRIPT CAPITAL A
    ('\u{1D49E}', 'C'), // MATHEMATICAL SCRIPT CAPITAL C
    ('\u{1D49F}', 'D'), // MATHEMATICAL SCRIPT CAPITAL D
    ('\u{1D4A2}', 'G'), // MATHEMATICAL SCRIPT CAPITAL G
    ('\u{1D4A5}', 'J'), // MATHEMATICAL SCRIPT CAPITAL J
    ('\u{1D4A6}', 'K'), // MATHEMATICAL SCRIPT CAPITAL K
    ('\u{1D4A9}', 'N'), // MATHEMATICAL SCRIPT CAPITAL N
    ('\u{1D4AA}', 'O'), // MATHEMATICAL SCRIPT CAPITAL O
    ('\u{1D4AB}', 'P'), // MATHEMATICAL SCRIPT CAPITAL P
    ('\u{1D4AC}', 'Q'), // MATHEMATICAL SCRIPT CAPITAL Q
    ('\u{1D4AE}', 'S'), // MATHEMATICAL SCRIPT CAPITAL S
    ('\u{1D4AF}', 'T'), // MATHEMATICAL SCRIPT CAPITAL T
    ('\u{1D4B0}', 'U'), // MATHEMATICAL SCRIPT CAPITAL U
    ('\u{1D4B1}', 'V'), // MATHEMATICAL SCRIPT CAPITAL V
    ('\u{1D4B2}', 'W'), // MATHEMATICAL SCRIPT CAPITAL W
    ('\u{1D4B3}', 'X'), // MATHEMATICAL SCRIPT CAPITAL X
    ('\u{1D4B4}', 'Y'), // MATHEMATICAL SCRIPT CAPITAL Y
    ('\u{1D4B5}', 'Z'), // MATHEMATICAL SCRIPT CAPITAL Z
    ('\u{1D4B6}', 'a'), // MATHEMATICAL SCRIPT SMALL A
    ('\u{1D4B7}', 'b'), // MATHEMATICAL SCRIPT SMALL B
    ('\u{1D4B8}', 'c'), // MATHEMATICAL SCRIPT SMALL C
    ('\u{1D4B9}', 'd'), // MATHEMATICAL SCRIPT SMALL D
    ('\u{1D4BB}', 'f'), // MATHEMATICAL SCRIPT SMALL F
    ('\u{1D4BD}', 'h'), // MATHEMATICAL SCRIPT SMALL H
    ('\u{1D4BE}', 'i'), // MATHEMATICAL SCRIPT SMALL I
    ('\u{1D4BF}', 'j'), // MATHEMATICAL SCRIPT SMALL J
    ('\u{1D4C0}', 'k'), // MATHEMATICAL SCRIPT SMALL K
    ('\u{1D4C1}', 'l'), // MATHEMATICAL SCRIPT SMALL L
    ('\u{1D4C2}', 'm'), // MATHEMATICAL SCRIPT SMALL M
    ('\u{1D4C3}', 'n'), // MATHEMATICAL SCRIPT SMALL N
    ('\u{1D4C5}', 'p'), // MATHEMATICAL SCRIPT SMALL P
    ('\u{1D4C6}', 'q'), // MATHEMATICAL SCRIPT SMALL Q
    ('\u{1D4C7}', 'r'), // MATHEMATICAL SCRIPT SMALL R
    ('\u{1D4C8}', 's'), // MATHEMATICAL SCRIPT SMALL S
    ('\u{1D4C9}', 't'), // MATHEMATICAL SCRIPT SMALL T
    ('\u{1D4CA}', 'u'), // MATHEMATICAL SCRIPT SMALL U
    ('\u{1D4CB}', 'v'), // MATHEMATICAL SCRIPT SMALL V
    ('\u{1D4CC}', 'w'), // MATHEMATICAL SCRIPT SMALL W
    ('\u{1D4CD}', 'x'), // MATHEMATICAL SCRIPT SMALL X
    ('\u{1D4CE}', 'y'), // MATHEMATICAL SCRIPT SMALL Y
    ('\u{1D4CF}', 'z'), // MATHEMATICAL SCRIPT SMALL Z
    ('\u{1D4D0}', 'A'), // MATHEMATICAL BOLD SCRIPT CAPITAL A
    ('\u{1D4D1}', 'B'), // MATHEMATICAL BOLD SCRIPT CAPITAL B
    ('\u{1D4D2}', 'C'), // MATHEMATICAL BOLD SCRIPT CAPITAL C
    ('\u{1D4D3}', 'D'), // MATHEMATICAL BOLD SCRIPT CAPITAL D
    ('\u{1D4D4}', 'E'), // MATHEMATICAL BOLD SCRIPT CAPITAL E
    ('\u{1D4D5}', 'F'), // MATHEMATICAL BOLD SCRIPT CAPITAL F
    ('\u{1D4D6}', 'G'), // MATHEMATICAL BOLD SCRIPT CAPITAL G
    ('\u{1D4D7}', 'H'), // MATHEMATICAL BOLD SCRIPT CAPITAL H
    ('\u{1D4D8}', 'I'), // MATHEMATICAL BOLD SCRIPT CAPITAL I
    ('\u{1D4D9}', 'J'), // MATHEMATICAL BOLD SCRIPT CAPITAL J
    ('\u{1D4DA}', 'K'), // MATHEMATICAL BOLD SCRIPT CAPITAL K
    ('\u{1D4DB}', 'L'), // MATHEMATICAL BOLD SCRIPT CAPITAL L
    ('\u{1D4DC}', 'M'), // MATHEMATICAL BOLD SCRIPT CAPITAL M
    ('\u{1D4DD}', 'N'), // MATHEMATICAL BOLD SCRIPT CAPITAL N
    ('\u{1D4DE}', 'O'), // MATHEMATICAL BOLD SCRIPT CAPITAL O
    ('\u{1D4DF}', 'P'), // MATHEMATICAL BOLD SCRIPT CAPITAL P
    ('\u{1D4E0}', 'Q'), // MATHEMATICAL BOLD SCRIPT CAPITAL Q
    ('\u{1D4E1}', 'R'), // MATHEMATICAL BOLD SCRIPT CAPITAL R
    ('\u{1D4E2}', 'S'), // MATHEMATICAL BOLD SCRIPT CAPITAL S
    ('\u{1D4E3}', 'T'), // MATHEMATICAL BOLD SCRIPT CAPITAL T
    ('\u{1D4E4}', 'U'), // MATHEMATICAL BOLD SCRIPT CAPITAL U
    ('\u{1D4E5}', 'V'), // MATHEMATICAL BOLD SCRIPT CAPITAL V
    ('\u{1D4E6}', 'W'), // MATHEMATICAL BOLD SCRIPT CAPITAL W
    ('\u{1D4E7}', 'X'), // MATHEMATICAL BOLD SCRIPT CAPITAL X
    ('\u{1D4E8}', 'Y'), // MATHEMATICAL BOLD SCRIPT CAPITAL Y
    ('\u{1D4E9}', 'Z'), // MATHEMATICAL BOLD SCRIPT CAPITAL Z
    ('\u{1D4EA}', 'a'), // MATHEMATICAL BOLD SCRIPT SMALL A
    ('\u{1D4EB}', 'b'), // MATHEMATICAL BOLD SCRIPT SMALL B
    ('\u{1D4EC}', 'c'), // MATHEMATICAL BOLD SCRIPT SMALL C
    ('\u{1D4ED}', 'd'), // MATHEMATICAL BOLD SCRIPT SMALL D
    ('\u{1D4EE}', 'e'), // MATHEMATICAL BOLD SCRIPT SMALL E
    ('\u{1D4EF}', 'f'), // MATHEMATICAL BOLD SCRIPT SMALL F
    ('\u{1D4F0}', 'g'), // MATHEMATICAL BOLD SCRIPT SMALL G
    ('\u{1D4F1}', 'h'), // MATHEMATICAL BOLD SCRIPT SMALL H
    ('\u{1D4F2}', 'i'), // MATHEMATICAL BOLD SCRIPT SMALL I
    ('\u{1D4F3}', 'j'), // MATHEMATICAL BOLD SCRIPT SMALL J
    ('\u{1D4F4}', 'k'), // MATHEMATICAL BOLD SCRIPT SMALL K
    ('\u{1D4F5}', 'l'), // MATHEMATICAL BOLD SCRIPT SMALL L
    ('\u{1D4F6}', 'm'), // MATHEMATICAL BOLD SCRIPT SMALL M
    ('\u{1D4F7}', 'n'), // MATHEMATICAL BOLD SCRIPT SMALL N
    ('\u{1D4F8}', 'o'), // MATHEMATICAL BOLD SCRIPT SMALL O
    ('\u{1D4F9}', 'p'), // MATHEMATICAL BOLD SCRIPT SMALL P
    ('\u{1D4FA}', 'q'), // MATHEMATICAL BOLD SCRIPT SMALL Q
    ('\u{1D4FB}', 'r'), // MATHEMATICAL BOLD SCRIPT SMALL R
    ('\u{1D4FC}', 's'), // MATHEMATICAL BOLD SCRIPT SMALL S
    ('\u{1D4FD}', 't'), // MATHEMATICAL BOLD SCRIPT SMALL T
    ('\u{1D4FE}', 'u'), // MATHEMATICAL BOLD SCRIPT SMALL U
    ('\u{1D4FF}', 'v'), // MATHEMATICAL BOLD SCRIPT SMALL V
    ('\u{1D500}', 'w'), // MATHEMATICAL BOLD SCRIPT SMALL W
    ('\u{1D501}', 'x'), // MATHEMATICAL BOLD SCRIPT SMALL X
    ('\u{1D502}', 'y'), // MATHEMATICAL BOLD SCRIPT SMALL Y
    ('\u{1D503}', 'z'), // MATHEMATICAL BOLD SCRIPT SMALL Z
    ('\u{1D504}', 'A'), // MATHEMATICAL FRAKTUR CAPITAL A
    ('\u{1D505}', 'B'), // MATHEMATICAL FRAKTUR CAPITAL B
    ('\u{1D507}', 'D'), // MATHEMATICAL FRAKTUR CAPITAL D
    ('\u{1D508}', 'E'), // MATHEMATICAL FRAKTUR CAPITAL E
    ('\u{1D509}', 'F'), // MATHEMATICAL FRAKTUR CAPITAL F
    ('\u{1D50A}', 'G'), // MATHEMATICAL FRAKTUR CAPITAL G
    ('\u{1D50D}', 'J'), // MATHEMATICAL FRAKTUR CAPITAL J
    ('\u{1D50E}', 'K'), // MATHEMATICAL FRAKTUR CAPITAL K
    ('\u{1D50F}', 'L'), // MATHEMATICAL FRAKTUR CAPITAL L
    ('\u{1D510}', 'M'), // MATHEMATICAL FRAKTUR CAPITAL M
    ('\u{1D511}', 'N'), // MATHEMATICAL FRAKTUR CAPITAL N
    ('\u{1D512}', 'O'), // MATHEMATICAL FRAKTUR CAPITAL O
    ('\u{1D513}', 'P'), // MATHEMATICAL FRAKTUR CAPITAL P
    ('\u{1D514}', 'Q'), // MATHEMATICAL FRAKTUR CAPITAL Q
    ('\u{1D516}', 'S'), // MATHEMATICAL FRAKTUR CAPITAL S
    ('\u{1D517}', 'T'), // MATHEMATICAL FRAKTUR CAPITAL T
    ('\u{1D518}', 'U'), // MATHEMATICAL FRAKTUR CAPITAL U
    ('\u{1D519}', 'V'), // MATHEMATICAL FRAKTUR CAPITAL V
    ('\u{1D51A}', 'W'), // MATHEMATICAL FRAKTUR CAPITAL W
    ('\u{1D51B}', 'X'), // MATHEMATICAL FRAKTUR CAPITAL X
    ('\u{1D51C}', 'Y'), // MATHEMATICAL FRAKTUR CAPITAL Y
    ('\u{1D51E}', 'a'), // MATHEMATICAL FRAKTUR SMALL A
    ('\u{1D51F}', 'b'), // MATHEMATICAL FRAKTUR SMALL B
    ('\u{1D520}', 'c'), // MATHEMATICAL FRAKTUR SMALL C
    ('\u{1D521}', 'd'), // MATHEMATICAL FRAKTUR SMALL D
    ('\u{1D522}', 'e'), // MATHEMATICAL FRAKTUR SMALL E
    ('\u{1D523}', 'f'), // MATHEMATICAL FRAKTUR SMALL F
    ('\u{1D524}', 'g'), // MATHEMATICAL FRAKTUR SMALL G
    ('\u{1D525}', 'h'), // MATHEMATICAL FRAKTUR SMALL H
    ('\u{1D526}', 'i'), // MATHEMATICAL FRAKTUR SMALL I
    ('\u{1D527}', 'j'), // MATHEMATICAL FRAKTUR SMALL J
    ('\u{1D528}', 'k'), // MATHEMATICAL FRAKTUR SMALL K
    ('\u{1D529}', 'l'), // MATHEMATICAL FRAKTUR SMALL L
    ('\u{1D52A}', 'm'), // MATHEMATICAL FRAKTUR SMALL M
    ('\u{1D52B}', 'n'), // MATHEMATICAL FRAKTUR SMALL N
    ('\u{1D52C}', 'o'), // MATHEMATICAL FRAKTUR SMALL O
    ('\u{1D52D}', 'p'), // MATHEMATICAL FRAKTUR SMALL P
    ('\u{1D52E}', 'q'), // MATHEMATICAL FRAKTUR SMALL Q
    ('\u{1D52F}', 'r'), // MATHEMATICAL FRAKTUR SMALL R
    ('\u{1D530}', 's'), // MATHEMATICAL FRAKTUR SMALL S
    ('\u{1D531}', 't'), // MATHEMATICAL FRAKTUR SMALL T
    ('\u{1D532}', 'u'), // MATHEMATICAL FRAKTUR SMALL U
    ('\u{1D533}', 'v'), // MATHEMATICAL FRAKTUR SMALL V
    ('\u{1D534}', 'w'), // MATHEMATICAL FRAKTUR SMALL W
    ('\u{1D535}', 'x'), // MATHEMATICAL FRAKTUR SMALL X
    ('\u{1D536}', 'y'), // MATHEMATICAL FRAKTUR SMALL Y
    ('\u{1D537}', 'z'), // MATHEMATICAL FRAKTUR SMALL Z
    ('\u{1D538}', 'A'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL A
    ('\u{1D539}', 'B'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL B
    ('\u{1D53B}', 'D'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL D
    ('\u{1D53C}', 'E'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL E
    ('\u{1D53D}', 'F'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL F
    ('\u{1D53E}', 'G'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL G
    ('\u{1D540}', 'I'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL I
    ('\u{1D541}', 'J'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL J
    ('\u{1D542}', 'K'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL K
    ('\u{1D543}', 'L'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL L
    ('\u{1D544}', 'M'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL M
    ('\u{1D546}', 'O'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL O
    ('\u{1D54A}', 'S'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL S
    ('\u{1D54B}', 'T'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL T
    ('\u{1D54C}', 'U'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL U
    ('\u{1D54D}', 'V'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL V
    ('\u{1D54E}', 'W'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL W
    ('\u{1D54F}', 'X'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL X
    ('\u{1D550}', 'Y'), // MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
    ('\u{1D552}', 'a'), // MATHEMATICAL DOUBLE-STRUCK SMALL A
    ('\u{1D553}', 'b'), // MATHEMATICAL DOUBLE-STRUCK SMALL B
    ('\u{1D554}', 'c'), // MATHEMATICAL DOUBLE-STRUCK SMALL C
    ('\u{1D555}', 'd'), // MATHEMATICAL DOUBLE-STRUCK SMALL D
    ('\u{1D556}', 'e'), // MATHEMATICAL DOUBLE-STRUCK SMALL E
    ('\u{1D557}', 'f'), // MATHEMATICAL DOUBLE-STRUCK SMALL F
    ('\u{1D558}', 'g'), // MATHEMATICAL DOUBLE-STRUCK SMALL G
    ('\u{1D559}', 'h'), // MATHEMATICAL DOUBLE-STRUCK SMALL H
    ('\u{1D55A}', 'i'), // MATHEMATICAL DOUBLE-STRUCK SMALL I
    ('\u{1D55B}', 'j'), // MATHEMATICAL DOUBLE-STRUCK SMALL J
    ('\u{1D55C}', 'k'), // MATHEMATICAL DOUBLE-STRUCK SMALL K
    ('\u{1D55D}', 'l'), // MATHEMATICAL DOUBLE-STRUCK SMALL L
    ('\u{1D55E}', 'm'), // MATHEMATICAL DOUBLE-STRUCK SMALL M
    ('\u{1D55F}', 'n'), // MATHEMATICAL DOUBLE-STRUCK SMALL N
    ('\u{1D560}', 'o'), // MATHEMATICAL DOUBLE-STRUCK SMALL O
    ('\u{1D561}', 'p'), // MATHEMATICAL DOUBLE-STRUCK SMALL P
    ('\u{1D562}', 'q'), // MATHEMATICAL DOUBLE-STRUCK SMALL Q
    ('\u{1D563}', 'r'), // MATHEMATICAL DOUBLE-STRUCK SMALL R
    ('\u{1D564}', 's'), // MATHEMATICAL DOUBLE-STRUCK SMALL S
    ('\u{1D565}', 't'), // MATHEMATICAL DOUBLE-STRUCK SMALL T
    ('\u{1D566}', 'u'), // MATHEMATICAL DOUBLE-STRUCK SMALL U
    ('\u{1D567}', 'v'), // MATHEMATICAL DOUBLE-STRUCK SMALL V
    ('\u{1D568}', 'w'), // MATHEMATICAL DOUBLE-STRUCK SMALL W
    ('\u{1D569}', 'x'), // MATHEMATICAL DOUBLE-STRUCK SMALL X
    ('\u{1D56A}', 'y'), // MATHEMATICAL DOUBLE-STRUCK SMALL Y
    ('\u{1D56B}', 'z'), // MATHEMATICAL DOUBLE-STRUCK SMALL Z
    ('\u{1D56C}', 'A'), // MATHEMATICAL BOLD FRAKTUR CAPITAL A
    ('\u{1D56D}', 'B'), // MATHEMATICAL BOLD FRAKTUR CAPITAL B
    ('\u{1D56E}', 'C'), // MATHEMATICAL BOLD FRAKTUR CAPITAL C
    ('\u{1D56F}', 'D'), // MATHEMATICAL BOLD FRAKTUR CAPITAL D
    ('\u{1D570}', 'E'), // MATHEMATICAL BOLD FRAKTUR CAPITAL E
    ('\u{1D571}', 'F'), // MATHEMATICAL BOLD FRAKTUR CAPITAL F
    ('\u{1D572}', 'G'), // MATHEMATICAL BOLD FRAKTUR CAPITAL G
    ('\u{1D573}', 'H'), // MATHEMATICAL BOLD FRAKTUR CAPITAL H
    ('\u{1D574}', 'I'), // MATHEMATICAL BOLD FRAKTUR CAPITAL I
    ('\u{1D575}', 'J'), // MATHEMATICAL BOLD FRAKTUR CAPITAL J
    ('\u{1D576}', 'K'), // MATHEMATICAL BOLD FRAKTUR CAPITAL K
    ('\u{1D577}', 'L'), // MATHEMATICAL BOLD FRAKTUR CAPITAL L
    ('\u{1D578}', 'M'), // MATHEMATICAL BOLD FRAKTUR CAPITAL M
    ('\u{1D579}', 'N'), // MATHEMATICAL BOLD FRAKTUR CAPITAL N
    ('\u{1D57A}', 'O'), // MATHEMATICAL BOLD FRAKTUR CAPITAL O
    ('\u{1D57B}', 'P'), // MATHEMATICAL BOLD FRAKTUR CAPITAL P
    ('\u{1D57C}', 'Q'), // MATHEMATICAL BOLD FRAKTUR CAPITAL Q
    ('\u{1D57D}', 'R'), // MATHEMATICAL BOLD FRAKTUR CAPITAL R
    ('\u{1D57E}', 'S'), // MATHEMATICAL BOLD FRAKTUR CAPITAL S
    ('\u{1D57F}', 'T'), // MATHEMATICAL BOLD FRAKTUR CAPITAL T
    ('\u{1D580}', 'U'), // MATHEMATICAL BOLD FRAKTUR CAPITAL U
    ('\u{1D581}', 'V'), // MATHEMATICAL BOLD FRAKTUR CAPITAL V
    ('\u{1D582}', 'W'), // MATHEMATICAL BOLD FRAKTUR CAPITAL W
    ('\u{1D583}', 'X'), // MATHEMATICAL BOLD FRAKTUR CAPITAL X
    ('\u{1D584}', 'Y'), // MATHEMATICAL BOLD FRAKTUR CAPITAL Y
    ('\u{1D585}', 'Z'), // MATHEMATICAL BOLD FRAKTUR CAPITAL Z
    ('\u{1D586}', 'a'), // MATHEMATICAL BOLD FRAKTUR SMALL A
    ('\u{1D587}', 'b'), // MATHEMATICAL BOLD FRAKTUR SMALL B
    ('\u{1D588}', 'c'), // MATHEMATICAL BOLD FRAKTUR SMALL C
    ('\u{1D589}', 'd'), // MATHEMATICAL BOLD FRAKTUR SMALL D
    ('\u{1D58A}', 'e'), // MATHEMATICAL BOLD FRAKTUR SMALL E
    ('\u{1D58B}', 'f'), // MATHEMATICAL BOLD FRAKTUR SMALL F
    ('\u{1D58C}', 'g'), // MATHEMATICAL BOLD FRAKTUR SMALL G
    ('\u{1D58D}', 'h'), // MATHEMATICAL BOLD FRAKTUR SMALL H
    ('\u{1D58E}', 'i'), // MATHEMATICAL BOLD FRAKTUR SMALL I
    ('\u{1D58F}', 'j'), // MATHEMATICAL BOLD FRAKTUR SMALL J
    ('\u{1D590}', 'k'), // MATHEMATICAL BOLD FRAKTUR SMALL K
    ('\u{1D591}', 'l'), // MATHEMATICAL BOLD FRAKTUR SMALL L
    ('\u{1D592}', 'm'), // MATHEMATICAL BOLD FRAKTUR SMALL M
    ('\u{1D593}', 'n'), // MATHEMATICAL BOLD FRAKTUR SMALL N
    ('\u{1D594}', 'o'), // MATHEMATICAL BOLD FRAKTUR SMALL O
    ('\u{1D595}', 'p'), // MATHEMATICAL BOLD FRAKTUR SMALL P
    ('\u{1D596}', 'q'), // MATHEMATICAL BOLD FRAKTUR SMALL Q
    ('\u{1D597}', 'r'), // MATHEMATICAL BOLD FRAKTUR SMALL R
    ('\u{1D598}', 's'), // MATHEMATICAL BOLD FRAKTUR SMALL S
    ('\u{1D599}', 't'), // MATHEMATICAL BOLD FRAKTUR SMALL T
    ('\u{1D59A}', 'u'), // MATHEMATICAL BOLD FRAKTUR SMALL U
    ('\u{1D59B}', 'v'), // MATHEMATICAL BOLD FRAKTUR SMALL V
    ('\u{1D59C}', 'w'), // MATHEMATICAL BOLD FRAKTUR SMALL W
    ('\u{1D59D}', 'x'), // MATHEMATICAL BOLD FRAKTUR SMALL X
    ('\u{1D59E}', 'y'), // MATHEMATICAL BOLD FRAKTUR SMALL Y
    ('\u{1D59F}', 'z'), // MATHEMATICAL BOLD FRAKTUR SMALL Z
    ('\u{1D5A0}', 'A'), // MATHEMATICAL SANS-SERIF CAPITAL A
    ('\u{1D5A1}', 'B'), // MATHEMATICAL SANS-SERIF CAPITAL B
    ('\u{1D5A2}', 'C'), // MATHEMATICAL SANS-SERIF CAPITAL C
    ('\u{1D5A3}', 'D'), // MATHEMATICAL SANS-SERIF CAPITAL D
    ('\u{1D5A4}', 'E'), // MATHEMATICAL SANS-SERIF CAPITAL E
    ('\u{1D5A5}', 'F'), // MATHEMATICAL SANS-SERIF CAPITAL F
    ('\u{1D5A6}', 'G'), // MATHEMATICAL SANS-SERIF CAPITAL G
    ('\u{1D5A7}', 'H'), // MATHEMATICAL SANS-SERIF CAPITAL H
    ('\u{1D5A8}', 'I'), // MATHEMATICAL SANS-SERIF CAPITAL I
    ('\u{1D5A9}', 'J'), // MATHEMATICAL SANS-SERIF CAPITAL J
    ('\u{1D5AA}', 'K'), // MATHEMATICAL SANS-SERIF CAPITAL K
    ('\u{1D5AB}', 'L'), // MATHEMATICAL SANS-SERIF CAPITAL L
    ('\u{1D5AC}', 'M'), // MATHEMATICAL SANS-SERIF CAPITAL M
    ('\u{1D5AD}', 'N'), // MATHEMATICAL SANS-SERIF CAPITAL N
    ('\u{1D5AE}', 'O'), // MATHEMATICAL SANS-SERIF CAPITAL O
    ('\u{1D5AF}', 'P'), // MATHEMATICAL SANS-SERIF CAPITAL P
    ('\u{1D5B0}', 'Q'), // MATHEMATICAL SANS-SERIF CAPITAL Q
    ('\u{1D5B1}', 'R'), // MATHEMATICAL SANS-SERIF CAPITAL R
    ('\u{1D5B2}', 'S'), // MATHEMATICAL SANS-SERIF CAPITAL S
    ('\u{1D5B3}', 'T'), // MATHEMATICAL SANS-SERIF CAPITAL T
    ('\u{1D5B4}', 'U'), // MATHEMATICAL SANS-SERIF CAPITAL U
    ('\u{1D5B5}', 'V'), // MATHEMATICAL SANS-SERIF CAPITAL V
    ('\u{1D5B6}', 'W'), // MATHEMATICAL SANS-SERIF CAPITAL W
    ('\u{1D5B7}', 'X'), // MATHEMATICAL SANS-SERIF CAPITAL X
    ('\u{1D5B8}', 'Y'), // MATHEMATICAL SANS-SERIF CAPITAL Y
    ('\u{1D5B9}', 'Z'), // MATHEMATICAL SANS-SERIF CAPITAL Z
    ('\u{1D5BA}', 'a'), // MATHEMATICAL SANS-SERIF SMALL A
    ('\u{1D5BB}', 'b'), // MATHEMATICAL SANS-SERIF SMALL B
    ('\u{1D5BC}', 'c'), // MATHEMATICAL SANS-SERIF SMALL C
    ('\u{1D5BD}', 'd'), // MATHEMATICAL SANS-SERIF SMALL D
    ('\u{1D5BE}', 'e'), // MATHEMATICAL SANS-SERIF SMALL E
    ('\u{1D5BF}', 'f'), // MATHEMATICAL SANS-SERIF SMALL F
    ('\u{1D5C0}', 'g'), // MATHEMATICAL SANS-SERIF SMALL G
    ('\u{1D5C1}', 'h'), // MATHEMATICAL SANS-SERIF SMALL H
    ('\u{1D5C2}', 'i'), // MATHEMATICAL SANS-SERIF SMALL I
    ('\u{1D5C3}', 'j'), // MATHEMATICAL SANS-SERIF SMALL J
    ('\u{1D5C4}', 'k'), // MATHEMATICAL SANS-SERIF SMALL K
    ('\u{1D5C5}', 'l'), // MATHEMATICAL SANS-SERIF SMALL L
    ('\u{1D5C6}', 'm'), // MATHEMATICAL SANS-SERIF SMALL M
    ('\u{1D5C7}', 'n'), // MATHEMATICAL SANS-SERIF SMALL N
    ('\u{1D5C8}', 'o'), // MATHEMATICAL SANS-SERIF SMALL O
    ('\u{1D5C9}', 'p'), // MATHEMATICAL SANS-SERIF SMALL P
    ('\u{1D5CA}', 'q'), // MATHEMATICAL SANS-SERIF SMALL Q
    ('\u{1D5CB}', 'r'), // MATHEMATICAL SANS-SERIF SMALL R
    ('\u{1D5CC}', 's'), // MATHEMATICAL SANS-SERIF SMALL S
    ('\u{1D5CD}', 't'), // MATHEMATICAL SANS-SERIF SMALL T
    ('\u{1D5CE}', 'u'), // MATHEMATICAL SANS-SERIF SMALL U
    ('\u{1D5CF}', 'v'), // MATHEMATICAL SANS-SERIF SMALL V
    ('\u{1D5D0}', 'w'), // MATHEMATICAL SANS-SERIF SMALL W
    ('\u{1D5D1}', 'x'), // MATHEMATICAL SANS-SERIF SMALL X
    ('\u{1D5D2}', 'y'), // MATHEMATICAL SANS-SERIF SMALL Y
    ('\u{1D5D3}', 'z'), // MATHEMATICAL SANS-SERIF SMALL Z
    ('\u{1D5D4}', 'A'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL A
    ('\u{1D5D5}', 'B'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL B
    ('\u{1D5D6}', 'C'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL C
    ('\u{1D5D7}', 'D'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL D
    ('\u{1D5D8}', 'E'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL E
    ('\u{1D5D9}', 'F'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL F
    ('\u{1D5DA}', 'G'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL G
    ('\u{1D5DB}', 'H'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL H
    ('\u{1D5DC}', 'I'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL I
    ('\u{1D5DD}', 'J'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL J
    ('\u{1D5DE}', 'K'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL K
    ('\u{1D5DF}', 'L'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL L
    ('\u{1D5E0}', 'M'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL M
    ('\u{1D5E1}', 'N'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL N
    ('\u{1D5E2}', 'O'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL O
    ('\u{1D5E3}', 'P'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL P
    ('\u{1D5E4}', 'Q'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL Q
    ('\u{1D5E5}', 'R'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL R
    ('\u{1D5E6}', 'S'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL S
    ('\u{1D5E7}', 'T'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL T
    ('\u{1D5E8}', 'U'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL U
    ('\u{1D5E9}', 'V'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL V
    ('\u{1D5EA}', 'W'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL W
    ('\u{1D5EB}', 'X'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL X
    ('\u{1D5EC}', 'Y'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL Y
    ('\u{1D5ED}', 'Z'), // MATHEMATICAL SANS-SERIF BOLD CAPITAL Z
    ('\u{1D5EE}', 'a'), // MATHEMATICAL SANS-SERIF BOLD SMALL A
    ('\u{1D5EF}', 'b'), // MATHEMATICAL SANS-SERIF BOLD SMALL B
    ('\u{1D5F0}', 'c'), // MATHEMATICAL SANS-SERIF BOLD SMALL C
    ('\u{1D5F1}', 'd'), // MATHEMATICAL SANS-SERIF BOLD SMALL D
    ('\u{1D5F2}', 'e'), // MATHEMATICAL SANS-SERIF BOLD SMALL E
    ('\u{1D5F3}', 'f'), // MATHEMATICAL SANS-SERIF BOLD SMALL F
    ('\u{1D5F4}', 'g'), // MATHEMATICAL SANS-SERIF BOLD SMALL G
    ('\u{1D5F5}', 'h'), // MATHEMATICAL SANS-SERIF BOLD SMALL H
    ('\u{1D5F6}', 'i'), // MATHEMATICAL SANS-SERIF BOLD SMALL I
    ('\u{1D5F7}', 'j'), // MATHEMATICAL SANS-SERIF BOLD SMALL J
    ('\u{1D5F8}', 'k'), // MATHEMATICAL SANS-SERIF BOLD SMALL K
    ('\u{1D5F9}', 'l'), // MATHEMATICAL SANS-SERIF BOLD SMALL L
    ('\u{1D5FA}', 'm'), // MATHEMATICAL SANS-SERIF BOLD SMALL M
    ('\u{1D5FB}', 'n'), // MATHEMATICAL SANS-SERIF BOLD SMALL N
    ('\u{1D5FC}', 'o'), // MATHEMATICAL SANS-SERIF BOLD SMALL O
    ('\u{1D5FD}', 'p'), // MATHEMATICAL SANS-SERIF BOLD SMALL P
    ('\u{1D5FE}', 'q'), // MATHEMATICAL SANS-SERIF BOLD SMALL Q
    ('\u{1D5FF}', 'r'), // MATHEMATICAL SANS-SERIF BOLD SMALL R
    ('\u{1D600}', 's'), // MATHEMATICAL SANS-SERIF BOLD SMALL S
    ('\u{1D601}', 't'), // MATHEMATICAL SANS-SERIF BOLD SMALL T
    ('\u{1D602}', 'u'), // MATHEMATICAL SANS-SERIF BOLD SMALL U
    ('\u{1D603}', 'v'), // MATHEMATICAL SANS-SERIF BOLD SMALL V
    ('\u{1D604}', 'w'), // MATHEMATICAL SANS-SERIF BOLD SMALL W
    ('\u{1D605}', 'x'), // MATHEMATICAL SANS-SERIF BOLD SMALL X
    ('\u{1D606}', 'y'), // MATHEMATICAL SANS-SERIF BOLD SMALL Y
    ('\u{1D607}', 'z'), // MATHEMATICAL SANS-SERIF BOLD SMALL Z
    ('\u{1D608}', 'A'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL A
    ('\u{1D609}', 'B'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL B
    ('\u{1D60A}', 'C'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL C
    ('\u{1D60B}', 'D'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL D
    ('\u{1D60C}', 'E'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL E
    ('\u{1D60D}', 'F'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL F
    ('\u{1D60E}', 'G'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL G
    ('\u{1D60F}', 'H'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL H
    ('\u{1D610}', 'I'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL I
    ('\u{1D611}', 'J'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL J
    ('\u{1D612}', 'K'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL K
    ('\u{1D613}', 'L'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL L
    ('\u{1D614}', 'M'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL M
    ('\u{1D615}', 'N'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL N
    ('\u{1D616}', 'O'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL O
    ('\u{1D617}', 'P'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL P
    ('\u{1D618}', 'Q'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL Q
    ('\u{1D619}', 'R'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL R
    ('\u{1D61A}', 'S'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL S
    ('\u{1D61B}', 'T'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL T
    ('\u{1D61C}', 'U'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL U
    ('\u{1D61D}', 'V'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL V
    ('\u{1D61E}', 'W'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL W
    ('\u{1D61F}', 'X'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL X
    ('\u{1D620}', 'Y'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL Y
    ('\u{1D621}', 'Z'), // MATHEMATICAL SANS-SERIF ITALIC CAPITAL Z
    ('\u{1D622}', 'a'), // MATHEMATICAL SANS-SERIF ITALIC SMALL A
    ('\u{1D623}', 'b'), // MATHEMATICAL SANS-SERIF ITALIC SMALL B
    ('\u{1D624}', 'c'), // MATHEMATICAL SANS-SERIF ITALIC SMALL C
    ('\u{1D625}', 'd'), // MATHEMATICAL SANS-SERIF ITALIC SMALL D
    ('\u{1D626}', 'e'), // MATHEMATICAL SANS-SERIF ITALIC SMALL E
    ('\u{1D627}', 'f'), // MATHEMATICAL SANS-SERIF ITALIC SMALL F
    ('\u{1D628}', 'g'), // MATHEMATICAL SANS-SERIF ITALIC SMALL G
    ('\u{1D629}', 'h'), // MATHEMATICAL SANS-SERIF ITALIC SMALL H
    ('\u{1D62A}', 'i'), // MATHEMATICAL SANS-SERIF ITALIC SMALL I
    ('\u{1D62B}', 'j'), // MATHEMATICAL SANS-SERIF ITALIC SMALL J
    ('\u{1D62C}', 'k'), // MATHEMATICAL SANS-SERIF ITALIC SMALL K
    ('\u{1D62D}', 'l'), // MATHEMATICAL SANS-SERIF ITALIC SMALL L
    ('\u{1D62E}', 'm'), // MATHEMATICAL SANS-SERIF ITALIC SMALL M
    ('\u{1D62F}', 'n'), // MATHEMATICAL SANS-SERIF ITALIC SMALL N
    ('\u{1D630}', 'o'), // MATHEMATICAL SANS-SERIF ITALIC SMALL O
    ('\u{1D631}', 'p'), // MATHEMATICAL SANS-SERIF ITALIC SMALL P
    ('\u{1D632}', 'q'), // MATHEMATICAL SANS-SERIF ITALIC SMALL Q
    ('\u{1D633}', 'r'), // MATHEMATICAL SANS-SERIF ITALIC SMALL R
    ('\u{1D634}', 's'), // MATHEMATICAL SANS-SERIF ITALIC SMALL S
    ('\u{1D635}', 't'), // MATHEMATICAL SANS-SERIF ITALIC SMALL T
    ('\u{1D636}', 'u'), // MATHEMATICAL SANS-SERIF ITALIC SMALL U
    ('\u{1D637}', 'v'), // MATHEMATICAL SANS-SERIF ITALIC SMALL V
    ('\u{1D638}', 'w'), // MATHEMATICAL SANS-SERIF ITALIC SMALL W
    ('\u{1D639}', 'x'), // MATHEMATICAL SANS-SERIF ITALIC SMALL X
    ('\u{1D63A}', 'y'), // MATHEMATICAL SANS-SERIF ITALIC SMALL Y
    ('\u{1D63B}', 'z'), // MATHEMATICAL SANS-SERIF ITALIC SMALL Z
    ('\u{1D63C}', 'A'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A
    ('\u{1D63D}', 'B'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B
    ('\u{1D63E}', 'C'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL C
    ('\u{1D63F}', 'D'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D
    ('\u{1D640}', 'E'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E
    ('\u{1D641}', 'F'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F
    ('\u{1D642}', 'G'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G
    ('\u{1D643}', 'H'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H
    ('\u{1D644}', 'I'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I
    ('\u{1D645}', 'J'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL J
    ('\u{1D646}', 'K'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K
    ('\u{1D647}', 'L'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L
    ('\u{1D648}', 'M'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M
    ('\u{1D649}', 'N'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N
    ('\u{1D64A}', 'O'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O
    ('\u{1D64B}', 'P'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P
    ('\u{1D64C}', 'Q'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Q
    ('\u{1D64D}', 'R'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R
    ('\u{1D64E}', 'S'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S
    ('\u{1D64F}', 'T'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T
    ('\u{1D650}', 'U'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U
    ('\u{1D651}', 'V'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL V
    ('\u{1D652}', 'W'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W
    ('\u{1D653}', 'X'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X
    ('\u{1D654}', 'Y'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y
    ('\u{1D655}', 'Z'), // MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Z
    ('\u{1D656}', 'a'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A
    ('\u{1D657}', 'b'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B
    ('\u{1D658}', 'c'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C
    ('\u{1D659}', 'd'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D
    ('\u{1D65A}', 'e'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E
    ('\u{1D65B}', 'f'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F
    ('\u{1D65C}', 'g'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G
    ('\u{1D65D}', 'h'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H
    ('\u{1D65E}', 'i'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I
    ('\u{1D65F}', 'j'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J
    ('\u{1D660}', 'k'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K
    ('\u{1D661}', 'l'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L
    ('\u{1D662}', 'm'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M
    ('\u{1D663}', 'n'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N
    ('\u{1D664}', 'o'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O
    ('\u{1D665}', 'p'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P
    ('\u{1D666}', 'q'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Q
    ('\u{1D667}', 'r'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R
    ('\u{1D668}', 's'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S
    ('\u{1D669}', 't'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T
    ('\u{1D66A}', 'u'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U
    ('\u{1D66B}', 'v'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V
    ('\u{1D66C}', 'w'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W
    ('\u{1D66D}', 'x'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X
    ('\u{1D66E}', 'y'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y
    ('\u{1D66F}', 'z'), // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z
    ('\u{1D670}', 'A'), // MATHEMATICAL MONOSPACE CAPITAL A
    ('\u{1D671}', 'B'), // MATHEMATICAL MONOSPACE CAPITAL B
    ('\u{1D672}', 'C'), // MATHEMATICAL MONOSPACE CAPITAL C
    ('\u{1D673}', 'D'), // MATHEMATICAL MONOSPACE CAPITAL D
    ('\u{1D674}', 'E'), // MATHEMATICAL MONOSPACE CAPITAL E
    ('\u{1D675}', 'F'), // MATHEMATICAL MONOSPACE CAPITAL F
    ('\u{1D676}', 'G'), // MATHEMATICAL MONOSPACE CAPITAL G
    ('\u{1D677}', 'H'), // MATHEMATICAL MONOSPACE CAPITAL H
    ('\u{1D678}', 'I'), // MATHEMATICAL MONOSPACE CAPITAL I
    ('\u{1D679}', 'J'), // MATHEMATICAL MONOSPACE CAPITAL J
    ('\u{1D67A}', 'K'), // MATHEMATICAL MONOSPACE CAPITAL K
    ('\u{1D67B}', 'L'), // MATHEMATICAL MONOSPACE CAPITAL L
    ('\u{1D67C}', 'M'), // MATHEMATICAL MONOSPACE CAPITAL M
    ('\u{1D67D}', 'N'), // MATHEMATICAL MONOSPACE CAPITAL N
    ('\u{1D67E}', 'O'), // MATHEMATICAL MONOSPACE CAPITAL O
    ('\u{1D67F}', 'P'), // MATHEMATICAL MONOSPACE CAPITAL P
    ('\u{1D680}', 'Q'), // MATHEMATICAL MONOSPACE CAPITAL Q
    ('\u{1D681}', 'R'), // MATHEMATICAL MONOSPACE CAPITAL R
    ('\u{1D682}', 'S'), // MATHEMATICAL MONOSPACE CAPITAL S
    ('\u{1D683}', 'T'), // MATHEMATICAL MONOSPACE CAPITAL T
    ('\u{1D684}', 'U'), // MATHEMATICAL MONOSPACE CAPITAL U
    ('\u{1D685}', 'V'), // MATHEMATICAL MONOSPACE CAPITAL V
    ('\u{1D686}', 'W'), // MATHEMATICAL MONOSPACE CAPITAL W
    ('\u{1D687}', 'X'), // MATHEMATICAL MONOSPACE CAPITAL X
    ('\u{1D688}', 'Y'), // MATHEMATICAL MONOSPACE CAPITAL Y
    ('\u{1D689}', 'Z'), // MATHEMATICAL MONOSPACE CAPITAL Z
    ('\u{1D68A}', 'a'), // MATHEMATICAL MONOSPACE SMALL A
    ('\u{1D68B}', 'b'), // MATHEMATICAL MONOSPACE SMALL B
    ('\u{1D68C}', 'c'), // MATHEMATICAL MONOSPACE SMALL C
    ('\u{1D68D}', 'd'), // MATHEMATICAL MONOSPACE SMALL D
    ('\u{1D68E}', 'e'), // MATHEMATICAL MONOSPACE SMALL E
    ('\u{1D68F}', 'f'), // MATHEMATICAL MONOSPACE SMALL F
    ('\u{1D690}', 'g'), // MATHEMATICAL MONOSPACE SMALL G
    ('\u{1D691}', 'h'), // MATHEMATICAL MONOSPACE SMALL H
    ('\u{1D692}', 'i'), // MATHEMATICAL MONOSPACE SMALL I
    ('\u{1D693}', 'j'), // MATHEMATICAL MONOSPACE SMALL J
    ('\u{1D694}', 'k'), // MATHEMATICAL MONOSPACE SMALL K
    ('\u{1D695}', 'l'), // MATHEMATICAL MONOSPACE SMALL L
    ('\u{1D696}', 'm'), // MATHEMATICAL MONOSPACE SMALL M
    ('\u{1D697}', 'n'), // MATHEMATICAL MONOSPACE SMALL N
    ('\u{1D698}', 'o'), // MATHEMATICAL MONOSPACE SMALL O
    ('\u{1D699}', 'p'), // MATHEMATICAL MONOSPACE SMALL P
    ('\u{1D69A}', 'q'), // MATHEMATICAL MONOSPACE SMALL Q
    ('\u{1D69B}', 'r'), // MATHEMATICAL MONOSPACE SMALL R
    ('\u{1D69C}', 's'), // MATHEMATICAL MONOSPACE SMALL S
    ('\u{1D69D}', 't'), // MATHEMATICAL MONOSPACE SMALL T
    ('\u{1D69E}', 'u'), // MATHEMATICAL MONOSPACE SMALL U
    ('\u{1D69F}', 'v'), // MATHEMATICAL MONOSPACE SMALL V
    ('\u{1D6A0}', 'w'), // MATHEMATICAL MONOSPACE SMALL W
    ('\u{1D6A1}', 'x'), // MATHEMATICAL MONOSPACE SMALL X
    ('\u{1D6A2}', 'y'), // MATHEMATICAL MONOSPACE SMALL Y
    ('\u{1D6A3}', 'z'), // MATHEMATICAL MONOSPACE SMALL Z
    ('\u{1D7CE}', '0'), // MATHEMATICAL BOLD DIGIT ZERO
    ('\u{1D7CF}', '1'), // MATHEMATICAL BOLD DIGIT ONE
    ('\u{1D7D0}', '2'), // MATHEMATICAL BOLD DIGIT TWO
    ('\u{1D7D1}', '3'), // MATHEMATICAL BOLD DIGIT THREE
    ('\u{1D7D2}', '4'), // MATHEMATICAL BOLD DIGIT FOUR
    ('\u{1D7D3}', '5'), // MATHEMATICAL BOLD DIGIT FIVE
    ('\u{1D7D4}', '6'), // MATHEMATICAL BOLD DIGIT SIX
    ('\u{1D7D5}', '7'), // MATHEMATICAL BOLD DIGIT SEVEN
    ('\u{1D7D6}', '8'), // MATHEMATICAL BOLD DIGIT EIGHT
    ('\u{1D7D7}', '9'), // MATHEMATICAL BOLD DIGIT NINE
    ('\u{1D7D8}', '0'), // MATHEMATICAL DOUBLE-STRUCK DIGIT ZERO
    ('\u{1D7D9}', '1'), // MATHEMATICAL DOUBLE-STRUCK DIGIT ONE
    ('\u{1D7DA}', '2'), // MATHEMATICAL DOUBLE-STRUCK DIGIT TWO
    ('\u{1D7DB}', '3'), // MATHEMATICAL DOUBLE-STRUCK DIGIT THREE
    ('\u{1D7DC}', '4'), // MATHEMATICAL DOUBLE-STRUCK DIGIT FOUR
    ('\u{1D7DD}', '5'), // MATHEMATICAL DOUBLE-STRUCK DIGIT FIVE
    ('\u{1D7DE}', '6'), // MATHEMATICAL DOUBLE-STRUCK DIGIT SIX
    ('\u{1D7DF}', '7'), // MATHEMATICAL DOUBLE-STRUCK DIGIT SEVEN
    ('\u{1D7E0}', '8'), // MATHEMATICAL DOUBLE-STRUCK DIGIT EIGHT
    ('\u{1D7E1}', '9'), // MATHEMATICAL DOUBLE-STRUCK DIGIT NINE
    ('\u{1D7E2}', '0'), // MATHEMATICAL SANS-SERIF DIGIT ZERO
    ('\u{1D7E3}', '1'), // MATHEMATICAL SANS-SERIF DIGIT ONE
    ('\u{1D7E4}', '2'), // MATHEMATICAL SANS-SERIF DIGIT TWO
    ('\u{1D7E5}', '3'), // MATHEMATICAL SANS-SERIF DIGIT THREE
    ('\u{1D7E6}', '4'), // MATHEMATICAL SANS-SERIF DIGIT FOUR
    ('\u{1D7E7}', '5'), // MATHEMATICAL SANS-SERIF DIGIT FIVE
    ('\u{1D7E8}', '6'), // MATHEMATICAL SANS-SERIF DIGIT SIX
    ('\u{1D7E9}', '7'), // MATHEMATICAL SANS-SERIF DIGIT SEVEN
    ('\u{1D7EA}', '8'), // MATHEMATICAL SANS-SERIF DIGIT EIGHT
    ('\u{1D7EB}', '9'), // MATHEMATICAL SANS-SERIF DIGIT NINE
    ('\u{1D7EC}', '0'), // MATHEMATICAL SANS-SERIF BOLD DIGIT ZERO
    ('\u{1D7ED}', '1'), // MATHEMATICAL SANS-SERIF BOLD DIGIT ONE
    ('\u{1D7EE}', '2'), // MATHEMATICAL SANS-SERIF BOLD DIGIT TWO
    ('\u{1D7EF}', '3'), // MATHEMATICAL SANS-SERIF BOLD DIGIT THREE
    ('\u{1D7F0}', '4'), // MATHEMATICAL SANS-SERIF BOLD DIGIT FOUR
    ('\u{1D7F1}', '5'), // MATHEMATICAL SANS-SERIF BOLD DIGIT FIVE
    ('\u{1D7F2}', '6'), // MATHEMATICAL SANS-SERIF BOLD DIGIT SIX
    ('\u{1D7F3}', '7'), // MATHEMATICAL SANS-SERIF BOLD DIGIT SEVEN
    ('\u{1D7F4}', '8'), // MATHEMATICAL SANS-SERIF BOLD DIGIT EIGHT
    ('\u{1D7F5}', '9'), // MATHEMATICAL SANS-SERIF BOLD DIGIT NINE
    ('\u{1D7F6}', '0'), // MATHEMATICAL MONOSPACE DIGIT ZERO
    ('\u{1D7F7}', '1'), // MATHEMATICAL MONOSPACE DIGIT ONE
    ('\u{1D7F8}', '2'), // MATHEMATICAL MONOSPACE DIGIT TWO
    ('\u{1D7F9}', '3'), // MATHEMATICAL MONOSPACE DIGIT THREE
    ('\u{1D7FA}', '4'), // MATHEMATICAL MONOSPACE DIGIT FOUR
    ('\u{1D7FB}', '5'), // MATHEMATICAL MONOSPACE DIGIT FIVE
    ('\u{1D7FC}', '6'), // MATHEMATICAL MONOSPACE DIGIT SIX
    ('\u{1D7FD}', '7'), // MATHEMATICAL MONOSPACE DIGIT SEVEN
    ('\u{1D7FE}', '8'), // MATHEMATICAL MONOSPACE DIGIT EIGHT
    ('\u{1D7FF}', '9'), // MATHEMATICAL MONOSPACE DIGIT NINE
    ('\u{1F12B}', 'C'), // CIRCLED ITALIC LATIN CAPITAL LETTER C
    ('\u{1F12C}', 'R'), // CIRCLED ITALIC LATIN CAPITAL LETTER R
    ('\u{1F130}', 'A'), // SQUARED LATIN CAPITAL LETTER A
    ('\u{1F131}', 'B'), // SQUARED LATIN CAPITAL LETTER B
    ('\u{1F132}', 'C'), // SQUARED LATIN CAPITAL LETTER C
    ('\u{1F133}', 'D'), // SQUARED LATIN CAPITAL LETTER D
    ('\u{1F134}', 'E'), // SQUARED LATIN CAPITAL LETTER E
    ('\u{1F135}', 'F'), // SQUARED LATIN CAPITAL LETTER F
    ('\u{1F136}', 'G'), // SQUARED LATIN CAPITAL LETTER G
    ('\u{1F137}', 'H'), // SQUARED LATIN CAPITAL LETTER H
    ('\u{1F138}', 'I'), // SQUARED LATIN CAPITAL LETTER I
    ('\u{1F139}', 'J'), // SQUARED LATIN CAPITAL LETTER J
    ('\u{1F13A}', 'K'), // SQUARED LATIN CAPITAL LETTER K
    ('\u{1F13B}', 'L'), // SQUARED LATIN CAPITAL LETTER L
    ('\u{1F13C}', 'M'), // SQUARED LATIN CAPITAL LETTER M
    ('\u{1F13D}', 'N'), // SQUARED LATIN CAPITAL LETTER N
    ('\u{1F13E}', 'O'), // SQUARED LATIN CAPITAL LETTER O
    ('\u{1F13F}', 'P'), // SQUARED LATIN CAPITAL LETTER P
    ('\u{1F140}', 'Q'), // SQUARED LATIN CAPITAL LETTER Q
    ('\u{1F141}', 'R'), // SQUARED LATIN CAPITAL LETTER R
    ('\u{1F142}', 'S'), // SQUARED LATIN CAPITAL LETTER S
    ('\u{1F143}', 'T'), // SQUARED LATIN CAPITAL LETTER T
    ('\u{1F144}', 'U'), // SQUARED LATIN CAPITAL LETTER U
    ('\u{1F145}', 'V'), // SQUARED LATIN CAPITAL LETTER V
    ('\u{1F146}', 'W'), // SQUARED LATIN CAPITAL LETTER W
    ('\u{1F147}', 'X'), // SQUARED LATIN CAPITAL LETTER X
    ('\u{1F148}', 'Y'), // SQUARED LATIN CAPITAL LETTER Y
    ('\u{1F149}', 'Z'), // SQUARED LATIN CAPITAL LETTER Z
    ('\u{1FBF0}', '0'), // SEGMENTED DIGIT ZERO
    ('\u{1FBF1}', '1'), // SEGMENTED DIGIT ONE
    ('\u{1FBF2}', '2'), // SEGMENTED DIGIT TWO
    ('\u{1FBF3}', '3'), // SEGMENTED DIGIT THREE
    ('\u{1FBF4}', '4'), // SEGMENTED DIGIT FOUR
    ('\u{1FBF5}', '5'), // SEGMENTED DIGIT FIVE
    ('\u{1FBF6}', '6'), // SEGMENTED DIGIT SIX
    ('\u{1FBF7}', '7'), // SEGMENTED DIGIT SEVEN
    ('\u{1FBF8}', '8'), // SEGMENTED DIGIT EIGHT
    ('\u{1FBF9}', '9'), // SEGMENTED DIGIT NINE
];

// Total: 1573 entries
