CONTEXT_KEYWORDS = {
    'Personal Identification': {
        'Identifiers': {
            'Canada SIN': ['social insurance number', 'sin', 'social insurance no'],
            'USA SSN': ['social security number', 'ssn', 'social security no'],
            'USA ITIN': ['individual taxpayer', 'itin', 'taxpayer identification'],
            'USA EIN': ['employer identification', 'ein', 'federal tax id', 'fein'],
            'UK NIN': ['national insurance number', 'nin', 'national insurance no'],
            'UK UTR': ['unique taxpayer reference', 'utr', 'tax reference'],
            'Singapore NIRC': ['national registration identity card', 'nric'],
            'Australia TFN': ['tax file number', 'tfn'],
            'India PAN': ['permanent account number', 'pan', 'pan card'],
            'India Aadhaar': ['aadhaar', 'aadhar', 'aadhaar number', 'uid number'],
            'Germany ID': ['identification number', 'personalausweis', 'german id'],
            'France NIR': ['insee', 'nir', 'french social security', 'securite sociale'],
            'Italy Codice Fiscale': ['codice fiscale', 'fiscal code', 'italian tax'],
            'Netherlands BSN': ['burgerservicenummer', 'bsn', 'citizen service number'],
            'South Korea RRN': ['resident registration', 'rrn', 'jumin deungnok'],
            'Japan My Number': ['my number', 'individual number', 'kojin bango'],
            'Mexico CURP': ['curp', 'clave unica', 'population registry'],
            'Mexico RFC': ['rfc', 'registro federal', 'federal taxpayer'],
            'South Africa ID': ['south african id', 'sa id', 'identity number'],
            'China Resident ID': ['resident id', 'identity card', 'shenfenzheng'],
            'Brazil CPF': ['cpf', 'cadastro de pessoas fisicas'],
            'Spain DNI/NIE': ['dni', 'nie', 'documento nacional'],
            'Canada BN': ['business number', 'canada bn', 'cra business'],
            'Poland PESEL': ['pesel', 'polish id', 'personal identification number'],
            'Sweden PIN': ['personnummer', 'swedish id', 'personal identity number'],
            'Portugal NIF': ['nif', 'contribuinte', 'tax identification'],
            'Switzerland AHV': ['ahv', 'avs', 'swiss social security'],
            'Turkey TC Kimlik': ['tc kimlik', 'turkish id', 'kimlik numarasi'],
        },
        'distance': 50,
    },
    'Credit Card Numbers': {
        'Identifiers': {
            'Visa': ['visa', 'cc', 'credit card', 'card number', 'card no'],
            'MasterCard': ['mastercard', 'mc', 'credit card', 'card number', 'card no'],
            'Amex': ['amex', 'american express', 'credit card', 'card number'],
            'Discover': ['discover', 'credit card', 'card number'],
            'JCB': ['jcb', 'credit card', 'card number'],
            'Diners Club': ['diners club', 'diners', 'credit card', 'card number'],
            'UnionPay': ['unionpay', 'union pay', 'credit card', 'card number'],
        },
        'distance': 50,
    },
    'Driver Licenses': {
        'Identifiers': {
            'Generic': ["driver's license", 'dl number', 'driving license', 'license id',
                        'driver license', 'drivers license', 'licence number'],
            'California DL': ["california driver's license", 'california dl'],
            'New York DL': ["new york driver's license", 'new york dl', 'ny dl'],
            'India DL': ["india driver's license", 'indian dl', 'driving licence india'],
            'Ontario': ["ontario driver's license", 'ontario dl'],
            'British Columbia': ["british columbia driver's license", 'bc dl'],
            'Alberta DL': ["alberta driver's license", 'alberta dl'],
            'Quebec DL': ["quebec driver's license", 'quebec dl'],
            'Nova Scotia DL': ["nova scotia driver's license", 'nova scotia dl'],
        },
        'distance': 50,
    },
    'Passports': {
        'Identifiers': {
            'Canada': ['canadian passport', 'canada passport', 'passport canada'],
            'USA Passport': ['us passport', 'usa passport', 'american passport', 'passport number'],
            'EU ETD': ['eu emergency travel document', 'etd', 'emergency travel'],
            'Japan Passport': ['japanese passport', 'japan passport'],
            'UK Passport': ['uk passport', 'british passport', 'united kingdom passport'],
            'Germany Passport': ['german passport', 'germany passport', 'reisepass'],
            'France Passport': ['french passport', 'france passport', 'passeport'],
            'India Passport': ['indian passport', 'india passport'],
            'China Passport': ['chinese passport', 'china passport'],
            'Australia Passport': ['australian passport', 'australia passport'],
            'Brazil Passport': ['brazilian passport', 'brazil passport'],
        },
        'distance': 50,
    },
    'Health Cards': {
        'Identifiers': {
            'Ontario': ['ontario health card', 'on health', 'on health card', 'ohip'],
            'British NHS': ['british nhs number', 'nhs number', 'nhs no', 'national health service'],
            'Australia Medicare': ['australian medicare', 'medicare number', 'medicare card'],
            'Alberta HC': ['alberta health card', 'alberta hc', 'ab health', 'ab health card', 'ahcip'],
            'Quebec HC': ['quebec health card', 'ramq', 'carte soleil'],
            'Nova Scotia HC': ['nova scotia health card', 'msi number', 'msi card'],
            'US DEA Number': ['dea number', 'dea registration', 'dea no', 'drug enforcement'],
            'US NPI': ['npi', 'national provider identifier', 'provider number'],
            'US MBI': ['mbi', 'medicare beneficiary', 'beneficiary identifier'],
        },
        'distance': 50,
    },
    'Bank Account Numbers': {
        'Identifiers': {
            'IBAN Generic': ['iban', 'international bank account number'],
            'USA Routing Number': ['routing number', 'aba routing', 'routing transit'],
            'Canada Bank Code': ['transit number', 'institution number', 'bank transit'],
            'UK Sort Code': ['sort code', 'uk sort', 'bank sort'],
            'SWIFT/BIC': ['swift', 'bic', 'bank identifier code', 'swift code'],
        },
        'distance': 50,
    },
    'Contact Information': {
        'Identifiers': {
            'Email Address': ['email', 'e-mail', 'email address', 'mail to', 'contact'],
            'US Phone Number': ['phone', 'telephone', 'tel', 'cell', 'mobile', 'call', 'fax'],
            'UK Phone Number': ['phone', 'telephone', 'tel', 'mobile', 'uk phone'],
            'E.164 Phone Number': ['phone', 'telephone', 'tel', 'mobile', 'contact number'],
            'IPv4 Address': ['ip address', 'ip', 'server', 'host', 'network'],
            'IPv6 Address': ['ip address', 'ipv6', 'server', 'host', 'network'],
            'MAC Address': ['mac address', 'hardware address', 'physical address', 'mac'],
        },
        'distance': 50,
    },
    'API Keys and Secrets': {
        'Identifiers': {
            'AWS Access Key': ['aws', 'amazon', 'access key', 'aws key'],
            'AWS Secret Key': ['aws secret', 'secret access key', 'aws_secret'],
            'Google API Key': ['google', 'gcp', 'google api', 'google cloud'],
            'GitHub Token (Classic)': ['github', 'gh token', 'personal access token'],
            'GitHub Token (Fine-Grained)': ['github', 'fine-grained', 'pat'],
            'GitHub OAuth Token': ['github oauth', 'oauth token'],
            'Stripe Secret Key': ['stripe', 'payment', 'stripe secret'],
            'Stripe Publishable Key': ['stripe', 'publishable', 'stripe key'],
            'Slack Bot Token': ['slack', 'bot token', 'slack bot'],
            'Slack User Token': ['slack', 'user token', 'slack user'],
            'Slack Webhook': ['slack', 'webhook', 'incoming webhook'],
            'Bearer Token': ['authorization', 'bearer', 'auth token'],
            'JWT Token': ['jwt', 'json web token', 'auth', 'token'],
            'Private Key': ['private key', 'rsa', 'ssh key', 'pem'],
            'Generic API Key': ['api key', 'api_key', 'apikey', 'api secret'],
            'Generic Secret Assignment': ['password', 'secret', 'credential', 'passwd'],
            'Database Connection String': ['database', 'db connection', 'connection string',
                                           'mongodb', 'postgres', 'mysql', 'redis'],
            'SendGrid API Key': ['sendgrid', 'email api'],
            'Twilio API Key': ['twilio', 'sms', 'messaging'],
            'Mailgun API Key': ['mailgun', 'email'],
            'NPM Token': ['npm', 'node package', 'npm token'],
            'PyPI Token': ['pypi', 'python package', 'pip'],
        },
        'distance': 80,
    },
    'Cryptocurrency': {
        'Identifiers': {
            'Bitcoin Address (Legacy)': ['bitcoin', 'btc', 'wallet', 'crypto'],
            'Bitcoin Address (Bech32)': ['bitcoin', 'btc', 'segwit', 'wallet'],
            'Ethereum Address': ['ethereum', 'eth', 'ether', 'wallet', 'crypto'],
            'Litecoin Address': ['litecoin', 'ltc', 'wallet'],
            'Bitcoin Cash Address': ['bitcoin cash', 'bch', 'wallet'],
            'Monero Address': ['monero', 'xmr', 'wallet'],
            'Ripple Address': ['ripple', 'xrp', 'wallet'],
        },
        'distance': 50,
    },
    'Vehicle Identification': {
        'Identifiers': {
            'VIN': ['vin', 'vehicle identification', 'vehicle id', 'chassis number',
                    'vehicle number'],
        },
        'distance': 50,
    },
    'Dates': {
        'Identifiers': {
            'Date ISO': ['date of birth', 'dob', 'birth date', 'birthday', 'born on',
                         'born', 'birthdate'],
            'Date US': ['date of birth', 'dob', 'birth date', 'birthday', 'born on',
                        'born', 'birthdate'],
            'Date EU': ['date of birth', 'dob', 'birth date', 'birthday', 'born on',
                        'born', 'birthdate'],
        },
        'distance': 50,
    },
    'URLs with Credentials': {
        'Identifiers': {
            'URL with Password': ['url', 'link', 'endpoint', 'connection', 'connect'],
            'URL with Token': ['url', 'link', 'endpoint', 'api', 'callback'],
        },
        'distance': 80,
    },
}
