

NORTH_AMERICA_CONTEXT = {
    'North America - United States': {
        'Identifiers': {
            'USA SSN': ['social security number', 'ssn', 'social security no'],
            'USA ITIN': ['individual taxpayer', 'itin', 'taxpayer identification'],
            'USA EIN': ['employer identification', 'ein', 'federal tax id', 'fein'],
            'USA Passport Book': ['us passport', 'usa passport', 'american passport', 'passport number', 'passport book'],
            'USA Passport Card': ['passport card', 'us passport card', 'usa passport card'],
            'USA Routing Number': ['routing number', 'aba routing', 'routing transit'],
            'US DEA Number': ['dea number', 'dea registration', 'dea no', 'drug enforcement'],
            'US NPI': ['npi', 'national provider identifier', 'provider number'],
            'US MBI': ['mbi', 'medicare beneficiary', 'beneficiary identifier', 'medicare number', 'medicare id'],
            'US DoD ID': ['dod id', 'military id', 'edipi', 'cac card', 'common access card', 'department of defense'],
            'US Known Traveler Number': ['known traveler', 'ktn', 'global entry', 'trusted traveler', 'pass id', 'nexus', 'sentri'],
            'US TSA PreCheck KTN': ['tsa precheck', 'tsa pre', 'precheck number', 'known traveler'],
            'US Phone Number': ['phone', 'telephone', 'tel', 'cell', 'mobile', 'call', 'fax'],
            'Alabama DL': ["alabama driver's license", 'alabama dl', 'al dl'],
            'Alaska DL': ["alaska driver's license", 'alaska dl', 'ak dl'],
            'Arizona DL': ["arizona driver's license", 'arizona dl', 'az dl'],
            'Arkansas DL': ["arkansas driver's license", 'arkansas dl', 'ar dl'],
            'California DL': ["california driver's license", 'california dl', 'ca dl'],
            'Colorado DL': ["colorado driver's license", 'colorado dl', 'co dl'],
            'Connecticut DL': ["connecticut driver's license", 'connecticut dl', 'ct dl'],
            'Delaware DL': ["delaware driver's license", 'delaware dl', 'de dl'],
            'DC DL': ["dc driver's license", 'district of columbia dl', 'dc dl'],
            'Florida DL': ["florida driver's license", 'florida dl', 'fl dl'],
            'Georgia DL': ["georgia driver's license", 'georgia dl', 'ga dl'],
            'Hawaii DL': ["hawaii driver's license", 'hawaii dl', 'hi dl'],
            'Idaho DL': ["idaho driver's license", 'idaho dl', 'id dl'],
            'Illinois DL': ["illinois driver's license", 'illinois dl', 'il dl'],
            'Indiana DL': ["indiana driver's license", 'indiana dl', 'in dl'],
            'Iowa DL': ["iowa driver's license", 'iowa dl', 'ia dl'],
            'Kansas DL': ["kansas driver's license", 'kansas dl', 'ks dl'],
            'Kentucky DL': ["kentucky driver's license", 'kentucky dl', 'ky dl'],
            'Louisiana DL': ["louisiana driver's license", 'louisiana dl', 'la dl'],
            'Maine DL': ["maine driver's license", 'maine dl', 'me dl'],
            'Maryland DL': ["maryland driver's license", 'maryland dl', 'md dl'],
            'Massachusetts DL': ["massachusetts driver's license", 'massachusetts dl', 'ma dl'],
            'Michigan DL': ["michigan driver's license", 'michigan dl', 'mi dl'],
            'Minnesota DL': ["minnesota driver's license", 'minnesota dl', 'mn dl'],
            'Mississippi DL': ["mississippi driver's license", 'mississippi dl', 'ms dl'],
            'Missouri DL': ["missouri driver's license", 'missouri dl', 'mo dl'],
            'Montana DL': ["montana driver's license", 'montana dl', 'mt dl'],
            'Nebraska DL': ["nebraska driver's license", 'nebraska dl', 'ne dl'],
            'Nevada DL': ["nevada driver's license", 'nevada dl', 'nv dl'],
            'New Hampshire DL': ["new hampshire driver's license", 'new hampshire dl', 'nh dl'],
            'New Jersey DL': ["new jersey driver's license", 'new jersey dl', 'nj dl'],
            'New Mexico DL': ["new mexico driver's license", 'new mexico dl', 'nm dl'],
            'New York DL': ["new york driver's license", 'new york dl', 'ny dl'],
            'North Carolina DL': ["north carolina driver's license", 'north carolina dl', 'nc dl'],
            'North Dakota DL': ["north dakota driver's license", 'north dakota dl', 'nd dl'],
            'Ohio DL': ["ohio driver's license", 'ohio dl', 'oh dl'],
            'Oklahoma DL': ["oklahoma driver's license", 'oklahoma dl', 'ok dl'],
            'Oregon DL': ["oregon driver's license", 'oregon dl', 'or dl'],
            'Pennsylvania DL': ["pennsylvania driver's license", 'pennsylvania dl', 'pa dl'],
            'Rhode Island DL': ["rhode island driver's license", 'rhode island dl', 'ri dl'],
            'South Carolina DL': ["south carolina driver's license", 'south carolina dl', 'sc dl'],
            'South Dakota DL': ["south dakota driver's license", 'south dakota dl', 'sd dl'],
            'Tennessee DL': ["tennessee driver's license", 'tennessee dl', 'tn dl'],
            'Texas DL': ["texas driver's license", 'texas dl', 'tx dl'],
            'Utah DL': ["utah driver's license", 'utah dl', 'ut dl'],
            'Vermont DL': ["vermont driver's license", 'vermont dl', 'vt dl'],
            'Virginia DL': ["virginia driver's license", 'virginia dl', 'va dl'],
            'Washington DL': ["washington driver's license", 'washington dl', 'wa dl'],
            'West Virginia DL': ["west virginia driver's license", 'west virginia dl', 'wv dl'],
            'Wisconsin DL': ["wisconsin driver's license", 'wisconsin dl', 'wi dl'],
            'Wyoming DL': ["wyoming driver's license", 'wyoming dl', 'wy dl'],
        },
        'distance': 50,
    },
    'North America - US Generic DL': {
        'Identifiers': {
            'Generic US DL': ["driver's license", 'dl number', 'driving license', 'license id', 'driver license', 'drivers license', 'licence number', 'license number', 'dl no'],
        },
        'distance': 50,
    },
    'North America - Canada': {
        'Identifiers': {
            'Canada SIN': ['social insurance number', 'sin', 'social insurance no'],
            'Canada BN': ['business number', 'canada bn', 'cra business'],
            'Canada Passport': ['canadian passport', 'canada passport', 'passport canada'],
            'Canada PR Card': ['permanent resident', 'pr card', 'permanent resident card', 'immigration', 'landed immigrant'],
            'Canada NEXUS': ['nexus', 'nexus card', 'pass id', 'trusted traveler', 'nexus number', 'cbp pass'],
            'Canada Bank Code': ['transit number', 'institution number', 'bank transit'],
            'Ontario DL': ["ontario driver's licence", 'ontario dl', 'on dl'],
            'Quebec DL': ["quebec driver's licence", 'quebec dl', 'qc dl', 'permis de conduire'],
            'British Columbia DL': ["british columbia driver's licence", 'bc dl', "bc driver's licence"],
            'Alberta DL': ["alberta driver's licence", 'alberta dl', 'ab dl'],
            'Saskatchewan DL': ["saskatchewan driver's licence", 'saskatchewan dl', 'sk dl'],
            'Manitoba DL': ["manitoba driver's licence", 'manitoba dl', 'mb dl'],
            'New Brunswick DL': ["new brunswick driver's licence", 'new brunswick dl', 'nb dl'],
            'Nova Scotia DL': ["nova scotia driver's licence", 'nova scotia dl', 'ns dl'],
            'PEI DL': ["pei driver's licence", 'prince edward island dl', 'pe dl'],
            'Newfoundland DL': ["newfoundland driver's licence", 'newfoundland dl', 'nl dl', 'labrador dl'],
            'Yukon DL': ["yukon driver's licence", 'yukon dl', 'yt dl'],
            'NWT DL': ["northwest territories driver's licence", 'nwt dl', 'nt dl'],
            'Nunavut DL': ["nunavut driver's licence", 'nunavut dl', 'nu dl'],
            'Ontario OHIP': ['ohip', 'ontario health card', 'ontario health insurance', 'health card number', 'ohip number'],
            'Quebec RAMQ': ['ramq', 'carte soleil', 'quebec health card', 'regie assurance maladie', 'health insurance quebec'],
            'BC MSP': ['bc msp', 'medical services plan', 'bc health card', 'bc phn', 'personal health number'],
            'Alberta AHCIP': ['ahcip', 'alberta health card', 'alberta phn', 'alberta health care insurance', 'ab health'],
            'Saskatchewan HC': ['saskatchewan health card', 'sk health', 'sk phn', 'saskatchewan health number'],
            'Manitoba PHIN': ['manitoba phin', 'manitoba health card', 'mb health', 'personal health identification number'],
            'New Brunswick HC': ['new brunswick health card', 'nb medicare', 'nb health', 'new brunswick medicare'],
            'Nova Scotia MSI': ['nova scotia msi', 'msi card', 'msi number', 'nova scotia health card', 'ns health'],
            'PEI HC': ['pei health card', 'prince edward island health', 'pe health card'],
            'Newfoundland MCP': ['newfoundland mcp', 'mcp card', 'mcp number', 'medical care plan', 'nl health card'],
        },
        'distance': 50,
    },
    'North America - Mexico': {
        'Identifiers': {
            'Mexico CURP': ['curp', 'clave unica', 'clave unica de registro', 'registro de poblacion', 'population registry'],
            'Mexico RFC': ['rfc', 'registro federal', 'registro federal de contribuyentes', 'federal taxpayer', 'tax id mexico'],
            'Mexico Clave Elector': ['clave de elector', 'credencial para votar', 'credencial elector', 'ine', 'ife', 'voter credential'],
            'Mexico INE CIC': ['cic', 'codigo de identificacion', 'ine cic', 'credential identification code'],
            'Mexico INE OCR': ['ocr', 'ine ocr', 'optical character recognition', 'credencial ocr'],
            'Mexico Passport': ['pasaporte mexicano', 'mexico passport', 'mexican passport', 'pasaporte'],
            'Mexico NSS': ['nss', 'numero de seguro social', 'imss', 'seguro social', 'instituto mexicano del seguro social'],
        },
        'distance': 50,
    },
}
