import re


NORTH_AMERICA_PATTERNS = {
    'North America - United States': {
        'USA SSN': re.compile(r'\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b'),
        'USA ITIN': re.compile(r'\b9\d{2}[-\s]?\d{2}[-\s]?\d{4}\b'),
        'USA EIN': re.compile(r'\b\d{2}-\d{7}\b'),
        'USA Passport Book': re.compile(r'\b(?:[A-Z]\d{8}|\d{9})\b'),
        'USA Passport Card': re.compile(r'\b[Cc]\d{8}\b'),
        'USA Routing Number': re.compile(r'\b\d{9}\b'),
        'US DEA Number': re.compile(r'\b[A-Z]{2}\d{7}\b'),
        'US NPI': re.compile(r'\b[12]\d{9}\b'),
        'US MBI': re.compile(r'\b[1-9][AC-HJKMNP-RT-Y][0-9AC-HJKMNP-RT-Y][0-9]-?[AC-HJKMNP-RT-Y][0-9AC-HJKMNP-RT-Y][0-9]-?[AC-HJKMNP-RT-Y]{2}[0-9]{2}\b'),
        'US DoD ID': re.compile(r'\b\d{10}\b'),
        'US Known Traveler Number': re.compile(r'\b\d{9}\b'),
        'US TSA PreCheck KTN': re.compile(r'\b(?:TT|TE|AC)\d{7,9}\b'),
        'US Phone Number': re.compile(r'(?<!\d)(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}(?!\d)'),
        'Alabama DL': re.compile(r'\b\d{1,8}\b'),
        'Alaska DL': re.compile(r'\b\d{1,7}\b'),
        'Arizona DL': re.compile(r'\b(?:[A-Z]\d{1,8}|[A-Z]{2}\d{2,5}|\d{9})\b'),
        'Arkansas DL': re.compile(r'\b\d{4,9}\b'),
        'California DL': re.compile(r'\b[A-Z]\d{7}\b'),
        'Colorado DL': re.compile(r'\b(?:\d{9}|[A-Z]\d{3,6}|[A-Z]{2}\d{2,5})\b'),
        'Connecticut DL': re.compile(r'\b\d{9}\b'),
        'Delaware DL': re.compile(r'\b\d{1,7}\b'),
        'DC DL': re.compile(r'\b(?:\d{7}|\d{9})\b'),
        'Florida DL': re.compile(r'\b[A-Z]\d{3}-?\d{3}-?\d{2}-?\d{3}-?\d\b'),
        'Georgia DL': re.compile(r'\b\d{7,9}\b'),
        'Hawaii DL': re.compile(r'\b(?:[A-Z]\d{8}|\d{9})\b'),
        'Idaho DL': re.compile(r'\b(?:[A-Z]{2}\d{6}[A-Z]|\d{9})\b'),
        'Illinois DL': re.compile(r'\b[A-Z]\d{3}-?\d{4}-?\d{4}\b'),
        'Indiana DL': re.compile(r'\b(?:[A-Z]\d{9}|\d{9,10})\b'),
        'Iowa DL': re.compile(r'\b(?:\d{9}|\d{3}[A-Z]{2}\d{4})\b'),
        'Kansas DL': re.compile(r'\b(?:[A-Z]\d[A-Z]\d[A-Z]|[A-Z]\d{2}-?\d{2}-?\d{4}|\d{9})\b'),
        'Kentucky DL': re.compile(r'\b(?:[A-Z]\d{8,9}|\d{9})\b'),
        'Louisiana DL': re.compile(r'\b\d{1,9}\b'),
        'Maine DL': re.compile(r'\b(?:\d{7}[A-Z]?|\d{8})\b'),
        'Maryland DL': re.compile(r'\b[A-Z]\d{12}\b'),
        'Massachusetts DL': re.compile(r'\b(?:[A-Z]\d{8}|\d{9})\b'),
        'Michigan DL': re.compile(r'\b[A-Z]\d{10,12}\b'),
        'Minnesota DL': re.compile(r'\b[A-Z]\d{12}\b'),
        'Mississippi DL': re.compile(r'\b\d{9}\b'),
        'Missouri DL': re.compile(r'\b(?:[A-Z]\d{5,9}|[A-Z]\d{6}R|\d{8}[A-Z]{2}|\d{9}[A-Z]|\d{9})\b'),
        'Montana DL': re.compile(r'\b(?:[A-Z]\d{8}|\d{9}|\d{13,14})\b'),
        'Nebraska DL': re.compile(r'\b(?:[A-Z]\d{8}|\d{1,7})\b'),
        'Nevada DL': re.compile(r'\b(?:\d{9,12}|X\d{8})\b'),
        'New Hampshire DL': re.compile(r'\b\d{2}[A-Z]{3}\d{5}\b'),
        'New Jersey DL': re.compile(r'\b[A-Z]\d{4}-?\d{5}-?\d{5}\b'),
        'New Mexico DL': re.compile(r'\b\d{8,9}\b'),
        'New York DL': re.compile(r'\b\d{3}\s?\d{3}\s?\d{3}\b'),
        'North Carolina DL': re.compile(r'\b\d{1,12}\b'),
        'North Dakota DL': re.compile(r'\b(?:[A-Z]{3}\d{6}|\d{9})\b'),
        'Ohio DL': re.compile(r'\b(?:[A-Z]{2}\d{6}|[A-Z]\d{4,8}|\d{8})\b'),
        'Oklahoma DL': re.compile(r'\b(?:[A-Z]\d{9}|\d{9})\b'),
        'Oregon DL': re.compile(r'\b\d{1,9}\b'),
        'Pennsylvania DL': re.compile(r'\b\d{2}\s?\d{3}\s?\d{3}\b'),
        'Rhode Island DL': re.compile(r'\b(?:\d{7}|V\d{6})\b'),
        'South Carolina DL': re.compile(r'\b\d{5,11}\b'),
        'South Dakota DL': re.compile(r'\b(?:\d{6,10}|\d{12})\b'),
        'Tennessee DL': re.compile(r'\b\d{7,9}\b'),
        'Texas DL': re.compile(r'\b\d{8}\b'),
        'Utah DL': re.compile(r'\b\d{4,10}\b'),
        'Vermont DL': re.compile(r'\b(?:\d{8}|\d{7}[A-Z])\b'),
        'Virginia DL': re.compile(r'\b(?:[A-Z]\d{8,11}|\d{9})\b'),
        'Washington DL': re.compile(r'\b[A-Z]{1,7}[A-Z0-9*]{5,11}\b'),
        'West Virginia DL': re.compile(r'\b(?:\d{7}|[A-Z]{1,2}\d{5,6})\b'),
        'Wisconsin DL': re.compile(r'\b[A-Z]\d{3}-?\d{4}-?\d{4}-?\d{2}\b'),
        'Wyoming DL': re.compile(r'\b\d{6}-?\d{3,4}\b'),
    },
    'North America - US Generic DL': {
        'Generic US DL': re.compile(r'\b[A-Z]{1,2}\d{4,14}\b'),
    },
    'North America - Canada': {
        'Canada SIN': re.compile(r'\b\d{3}[-\s]?\d{3}[-\s]?\d{3}\b'),
        'Canada BN': re.compile(r'\b\d{9}[A-Z]{2}\d{4}\b'),
        'Canada Passport': re.compile(r'\b[A-Z]{2}\d{6}\b'),
        'Canada PR Card': re.compile(r'\b[A-Z]{2}\d{7,10}\b'),
        'Canada NEXUS': re.compile(r'\b\d{9}\b'),
        'Canada Bank Code': re.compile(r'\b\d{5}-\d{3}\b'),
        'Ontario DL': re.compile(r'\b[A-Z]\d{4}-?\d{5}-?\d{5}\b'),
        'Quebec DL': re.compile(r'\b[A-Z]\d{12}\b'),
        'British Columbia DL': re.compile(r'\b\d{7}\b'),
        'Alberta DL': re.compile(r'\b(?:\d{6}-\d{3}|\d{5,9})\b'),
        'Saskatchewan DL': re.compile(r'\b\d{8}\b'),
        'Manitoba DL': re.compile(r'\b[A-Z]{2}-?[A-Z]{2}-?[A-Z]{2}-?[A-Z]\d{3}[A-Z]{2}\b'),
        'New Brunswick DL': re.compile(r'\b\d{5,7}\b'),
        'Nova Scotia DL': re.compile(r'\b[A-Z]{5}-?\d{3}-?\d{3}-?\d{3}\b'),
        'PEI DL': re.compile(r'\b\d{5,6}\b'),
        'Newfoundland DL': re.compile(r'\b[A-Z]\d{9}\b'),
        'Yukon DL': re.compile(r'\b\d{1,6}\b'),
        'NWT DL': re.compile(r'\b\d{6}\b'),
        'Nunavut DL': re.compile(r'\b\d{6}\b'),
        'Ontario OHIP': re.compile(r'\b\d{10}(?:\s?[A-Z]{2})?\b'),
        'Quebec RAMQ': re.compile(r'\b[A-Z]{4}\d{8}\b'),
        'BC MSP': re.compile(r'\b9\d{9}\b'),
        'Alberta AHCIP': re.compile(r'\b\d{9}\b'),
        'Saskatchewan HC': re.compile(r'\b\d{9}\b'),
        'Manitoba PHIN': re.compile(r'\b\d{9}\b'),
        'New Brunswick HC': re.compile(r'\b\d{9}\b'),
        'Nova Scotia MSI': re.compile(r'\b\d{10}\b'),
        'PEI HC': re.compile(r'\b\d{8}\b'),
        'Newfoundland MCP': re.compile(r'\b\d{12}\b'),
    },
    'North America - Mexico': {
        'Mexico CURP': re.compile(r'\b[A-Z]{4}\d{6}[HM][A-Z]{5}[A-Z0-9]\d\b'),
        'Mexico RFC': re.compile(r'\b[A-ZÑ&]{3,4}\d{6}[A-Z0-9]{3}\b'),
        'Mexico Clave Elector': re.compile(r'\b[A-Z]{6}\d{2}[01]\d[0-3]\d[0-3]\d[HM]\d{3}\b'),
        'Mexico INE CIC': re.compile(r'\b\d{9}\b'),
        'Mexico INE OCR': re.compile(r'\b\d{13}\b'),
        'Mexico Passport': re.compile(r'\b[A-Z]\d{8}\b'),
        'Mexico NSS': re.compile(r'\b\d{11}\b'),
    },
}
